### ISSUE TITLE
OR_BIBED_07 and OR_BIBED_01 errors

### ISSUE THREAD

**Issue by rydal** [google-pay/flutter-plugin#102]
Hi all,

I'm getting the following error when using Stripe as a payment gateway on Flutter using this library.

OR_BIBED_07 and OR_BIBED_01

OR_BIBED_07 happens when using live keys before the payment screen is rendered.
OR_BIBED_01 happens when using live keys after the payment screen is rendered.

Nothing reported on local logs or in Stripe according to their support..

Any ideas?

Thank you.
         Rob.

**Comment by rydal** [comment]
Ps,  this is on Android.

**Comment by JlUgia** [comment]
Hi Rob, can you share your payment configuration JSON (excluding secrets)?

**Comment by rydal** [comment]
{
  "provider": "google_pay",
  "data": {
    "environment": "PRODUCTION",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2018-10-31",
            "gatewayMerchantId": "***"
          }
        },
        "parameters": {
          "allowedCardNetworks": ["VISA", "MASTERCARD"],
          "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
          "billingAddressRequired": false,
          "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": false
          }
        }
      }
    ],
    "merchantInfo": {
      "merchantId": "** my email address as with Stripe",
      "merchantName": "** app name **"
    },
    "transactionInfo": {
      "countryCode": "GB",
      "currencyCode": "GBP"
    }
  }

**Comment by xmany** [comment]
Hi, I am having a same error, my configuration file looks to be valid

```
{
  "provider": "google_pay",
  "data": {
    "environment": "PRODUCTION",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2020-08-27",
            "stripe:publishableKey": "key"
          }
        },
        "parameters": {
          "allowedCardNetworks": ["VISA", "MASTERCARD"],
          "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
          "billingAddressRequired": false,
          "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": false
          }
        }
      }
    ],
    "merchantInfo": {
      "merchantId": "my_merchant_id",
      "merchantName": "name"
    },
    "transactionInfo": {
      "countryCode": "NZ",
      "currencyCode": "NZD"
    }
  }
}
```

**Comment by JlUgia** [comment]
Hello @xmany,
More details on the error are shared in the logs. See the [troubleshooting section in the Google Pay docs](https://developers.google.com/pay/api/android/support/troubleshooting#request-failed) to learn more.

Running `adb -d logcat -s WalletMerchantError` with your config the error is:

```
W WalletMerchantError: Error in loadPaymentData: Invalid stripe:publishableKey for current environment. Make sure you are using Stripe's test key.
```
The API is expecting a valid test key for the test environment.
Once you are ready testing your integration, you need to add your integration to [Google Pay's Business Console](https://pay.google.com/business/console) before you can flip the environment to `PRODUCTION`.

**Comment by xmany** [comment]
> Hello @xmany,
> More details on the error are shared in the logs. See the [troubleshooting section in the Google Pay docs](https://developers.google.com/pay/api/android/support/troubleshooting#request-failed) to learn more.
> 
> Running `adb -d logcat -s WalletMerchantError` with your config the error is:
> 
> ```
> W WalletMerchantError: Error in loadPaymentData: Invalid stripe:publishableKey for current environment. Make sure you are using Stripe's test key.
> ```
> The API is expecting a valid test key for the test environment.
> Once you are ready testing your integration, you need to add your integration to [Google Pay's Business Console](https://pay.google.com/business/console) before you can flip the environment to `PRODUCTION`.

Thanks for the explanation 🤠

**Comment by hybrid-technologies-vn** [comment]
@JlUgia 
I have got same issue.
I have try running `adb -d logcat -s WalletMerchantError` but nothing happens.
![image](https://user-images.githubusercontent.com/93751916/148486222-abcb6d1d-9250-431b-b096-f6bf9556a174.png)

**Comment by cungtrang0978** [comment]
@JlUgia
I have got same issue.
I have try running `adb -d logcat -s WalletMerchantError` but nothing happens.
![image](https://user-images.githubusercontent.com/55270893/148489869-840ac102-2e1b-4721-9ed6-caecf4ddd799.png)

**Comment by JlUgia** [comment]
Hi @cungtrang0978, the error will show up in the logs when you dismiss the error pop-up after attempting to pay with Google Pay.
Let me know if that helps.

**Comment by cungtrang0978** [comment]
@JlUgia Oh, when I tap Google Pay button, immediately an error popup will appear with content:
"Request Failed
An unexpected error has occurred. Please try again later. [OR_BIBED_07]"
I dismiss it and just got this log `[log] PlatformException(paymentCanceled, User canceled payment authorization, null, null)`.
I still dont know how to fix it.
Hope you can help.
Thanks

**Comment by JlUgia** [comment]
Hi @cungtrang0978, that's an error in your configuration.
Can you paste your JSON config obfuscating any secret values?

**Comment by cungtrang0978** [comment]
@JlUgia oh sorry, maybe I have not requested to Google Pay to integrate with my Android app. 😅
Thanks for your help.

**Comment by danil-slabukho** [comment]
> @JlUgia I have got same issue. I have try running `adb -d logcat -s WalletMerchantError` but nothing happens. ![image](https://user-images.githubusercontent.com/55270893/148489869-840ac102-2e1b-4721-9ed6-caecf4ddd799.png)

did you solve this problem?

**Comment by gerard2perez** [comment]
Hello guys in facing the same problem does anyone knows where can i find more information?

**Comment by BLRManyaTech** [comment]
Hi was facing issue same and onces we are trying hit button its taking automatically into success response

**Comment by gerard2perez** [comment]
Hello, I am working with capacitor using a custom plugin, and as I commented before I ran into the issue.
I had donde the registration on the app in the Bussiness Console.

And today y found a solution.

When I relsease a version in the **internal channel**, the app worked, but i have some other issues in my app.

So if anyone need to debug their app testing GPay.

You must build a signed APK and the install ir with adb

`adb install app-release.apk`

and use the power of Log.i("my tag", "content to debug")

to help you out to find out what's happening.

Hope it helps someone.

Greetings

**Comment by nolimitdev** [comment]
I can confirm that OR_BIBED_07 is also in case ENVIRONMENT_PRODUCTION and app is not aproved or waiting for review in Google Pay Console https://pay.google.com/business/console/ When app status is "Active" error goes away. It is really sad that google does not provide better error message even in console. In console we cen see that volley request fails with HTTP status 500 which indicates server error not user/developer error (HTTp status 400 should be used).

@gerard2perez Installing production (signed) app can be done via Android Studio UI - at left side click Build Variants and change Active Build Variant from debug to release.

**Comment by leopard0122** [comment]
Hello, everyone. nice to meet you. I have same issues. I completed buisnes profile
Please help me

**Comment by leopard0122** [comment]
![image](https://user-images.githubusercontent.com/102648904/215407525-3c4c3624-e3b8-4b97-bbdf-7135c871d746.png)

**Comment by APU-Stark** [comment]
share your GooglePayPaymentMethodLauncher.Config var. it should be on test if you are on debug. if you are on prod you need to release app on internal test or live.

**Comment by leopard0122** [comment]
this runs well on Test mode
only in production mode, I have this error

**Comment by APU-Stark** [comment]
i would suggest you to publish the app on internal testing mode to check google pay in prod mode.

**Comment by ShubhAppentus** [comment]
I implement google pay from google pay docs and when i am testing it it test environment i am getting an error "we couldn't complete this action. Try a different payment method or contact us. [OR_CCREU_02]" i spend almost 4 days to resolving this error but nothing helps for me. 
Anyone have any idea how to resolve this error and test google pay transaction for Test Environment

this is my json: 

{
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
        {
            "type": "CARD",
            "parameters": {
                "allowedAuthMethods": [
                    "PAN_ONLY",
                    "CRYPTOGRAM_3DS"
                ],
                "allowedCardNetworks": [
                    "AMEX",
                    "DISCOVER",
                    "JCB",
                    "MASTERCARD",
                    "VISA"
                ],
                "billingAddressRequired": true,
                "billingAddressParameters": {
                    "format": "FULL"
                }
            },
            "tokenizationSpecification": {
                "type": "PAYMENT_GATEWAY",
                "parameters": {
                    "gateway": "example",
                    "gatewayMerchantId": "BCR2DN4T7KHP7EJS"
                }
            }
        }
    ],
    "transactionInfo": {
        "totalPrice": "1000",
        "totalPriceStatus": "FINAL",
        "countryCode": "US",
        "currencyCode": "USD"
    },
    "merchantInfo": {
        "merchantName": "example"
    },
    "shippingAddressParameters": {
        "phoneNumberRequired": false,
        "allowedCountryCodes": [
            "US",
            "GB"
        ]
    },
    "shippingAddressRequired": true
}


Screen shot of the actual error: 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/124139857/228140752-45e31f7b-e6f6-4ef1-8c54-0afe60a684ad.png)

@leopard0122 Do you have any suggestion?
Please help me guys any suggestion appreciated

**Comment by oremlawi** [comment]
In my case, I got [OR_BIBED_07] error only in PRODUCTION mode when I click GPay button. And the solution for this was uploading a signed bundle (or apk) and test the app from an internal testing track.

So far, you can't test PRODUCTION mode from a debug version. You need to test it from a beta track.

**Comment by Matej-Hlatky** [comment]
> In my case, I got [OR_BIBED_07] error only in PRODUCTION mode when I click GPay button. And the solution for this was uploading a signed bundle (or apk) and test the app from an internal testing track.

I've had same issue.
In my case, building and signing PRODUCTION `Release` build was enough; don't need really upload to Google Play.
