### ISSUE TITLE
Add support for India

### ISSUE THREAD

**Issue by SITARAM-LAB** [google-pay/flutter-plugin#103]
As flutter is growing and getting popular day by day in India and without a payment gateway from google flutter remains incomplete in India.
India is a very big market please add support to collect paymentS using this plugin in India as well.
This is not an issue just a request.

Regards,
SITARAM LAB

**Comment by JlUgia** [comment]
Hello @SITARAM-LAB, thank you for the suggestion.
Google Pay uses UPI in India. This plugin uses the global API for Google Pay, and does not support UPI.
See #33 to learn more about how to transact with UPI on Flutter.
