### ISSUE TITLE
flutter pay not support arabic language

### ISSUE THREAD

**Issue by EngYasmeenMahmoud** [google-pay/flutter-plugin#110]
i use flutter pay in Arabic/English app
in Arabic language book with google pay button appeared as "مادختساب زجحلا"

do you have any way to control this text or remove 
![WhatsApp Image 2021-12-07 at 6 35 26 AM](https://user-images.githubusercontent.com/73816761/144967105-dd6ddfb9-63b8-4e73-82e9-ebe859eace20.jpeg)
it

**Comment by JlUgia** [comment]
Thank for flagging @EngYasmeenMahmoud.
Looking into it. Will push a fix as soon as we obtain the appropriate values.

**Comment by AbdArahman2001** [comment]
@JlUgia 
Is the problem solved?
I also use the Arabic language in my app.

**Comment by JlUgia** [comment]
The Google Pay button is receiving an update that transfers the drawing responsibility to Android.
This new button supports the Arabic language out of the box. I'll add the PR here when created.

**Comment by dmengelt** [comment]
We fixed the issue for the dynamic button for `ar` last week: https://github.com/google-pay/google-pay-button/issues/251

**Comment by JlUgia** [comment]
Published change in [`pay_android:1.1.0-beta01`](https://pub.dev/packages/pay_android/versions/1.1.0-beta01/changelog#110-beta01-2024-01-19) and [`pay:1.2.0-beta02`](https://pub.dev/packages/pay/versions/1.2.0-beta02/changelog#120-beta02-2024-01-21).
