### ISSUE TITLE
Google pay not supported

### ISSUE THREAD

**Issue by nmdv24** [google-pay/flutter-plugin#112]
Google Pay is not available in this device 
            - Huawei p30, 
            - LG G6, 
            - Samsung A8,
            - Redmi k30

All devices supported google services. What problem here?

**Comment by JlUgia** [comment]
Hi @nmdv24, take a look at the [full list with the technical requirements for Google Pay on Android](https://developers.google.com/pay/api/android/guides/setup).

**Comment by JlUgia** [comment]
Closing this one, feel free to reopen if the link does not help clarify.
