### ISSUE TITLE
adding bank card

### ISSUE THREAD

**Issue by Maxim-Gorin** [google-pay/flutter-plugin#114]
Can I add a bank card from the app? Or maybe I can at least invoke the native interface to add a map?

**Comment by JlUgia** [comment]
Hi @Maxim-Gorin, this plugin. uses Apple Pay and Google Pay to facilitate adding payments functionality to your applications, and hence, it does not define the underlying behavior of any of the providers. Adding/removing cards or managing other forms of payment can be done with the provider itself.
