### ISSUE TITLE
iOS Button is not showing in real device

### ISSUE THREAD

**Issue by AbirAhsan** [google-pay/flutter-plugin#116]
I am working with this package.  Everything is fine on my simulator but when I run it on my real device, then button is not visible.

**Comment by SI-IC** [comment]
@AbirAhsan Have the same problem. Did you solve it?

**Comment by jsmeke** [comment]
I'm also having this issue.

**Comment by ravilimbani2203** [comment]
@AbirAhsan please check Apple Pay is not support in many countries so check your country support apple pay or not

**Comment by jsmeke** [comment]
@ravilimbani2203 so if I'm in a non supported country the button will only show on the simulator?

**Comment by ravilimbani2203** [comment]
Yes

**Comment by ravilimbani2203** [comment]
> @ravilimbani2203 so if I'm in a non supported country the button will only show on the simulator?

Yes

**Comment by jsmeke** [comment]
But if have to develop for a country that has Apple Pay, but it's not currently supported in my country, how can I test it on a real device? is there any workaround?

**Comment by asepindrak** [comment]
Same issue here, button is showing on simulator but not showing on real device, how to solve it? I also get apple_pay.cert but not know where to place that certificate.

**Comment by eedyGarcia** [comment]
I'm from Mexico, I have the same problem, I've been trying to solve it for weeks and I just haven't succeeded, I've already done everything that the Apple documentation asks for

**Comment by JlUgia** [comment]
This issue doesn't seem to be relevant to this package.
This [StackOverflow post](https://stackoverflow.com/questions/43120587/apple-pay-works-on-simulator-but-not-on-device) has some more info on how Apple Pay handles test accounts.

**Comment by GangadharNilesh** [comment]
@[AbirAhsan](https://github.com/AbirAhsan) Have the same problem. Did you solve it?

**Comment by JudahMcNicholl** [comment]
Hi, 

https://stackoverflow.com/questions/43120587/apple-pay-works-on-simulator-but-not-on-device

Second answer where it says to set up a sandbox user, sign in via apple id with that sandbox user then add a card to the wallet on the real device solved this for me.

**Comment by DinhNguyen992** [comment]
Hi @AbirAhsan 
I am developer in Vietnamese I using lib google pay but IOS button not showing in real device . I research problem . 
I read document Sandbox Testing then nation no support Sandbox testing ? I am from Vietnamese .
Please hep me .

**Comment by JlUgia** [comment]
Hi @DinhNguyen992, [Apple Pay does not seem to support transactions for Vietnam at the moment](https://developer.apple.com/apple-pay/payment-platforms/).

Closing the case, since the original issue is resolved.

**Comment by DinhNguyen992** [comment]
@JlUgia 
Thanks I find document apple vs read this .
