### ISSUE TITLE
OR_BIBED_07 error when i turn app into production mode

### ISSUE THREAD

**Issue by alishahbaz659** [google-pay/flutter-plugin#118]
I am getting OR_BIBED_07 error in android application when i set enviroment to prodcution. Google pay business console is giving no option to connect to android app. it says "There are no Android apps currently associated with examplel@gmail.com as the account owner, admin or user. To take action, you must be in one of those roles"

**Comment by JlUgia** [comment]
Hi @alishahbaz659. The list of Android apps you see in Google Pay's Business Console is directly synced from Google Play. Make sure to add your email address in Google Pay's Business Console (examplel@gmail.com) as an account owner, admin, or user in your applications using [Google Play's console](https://play.google.com/console/about/).

**Comment by alishahbaz659** [comment]
Thank you for your email
