### ISSUE TITLE
Unrecognized app. Please make sure you trust the app before proceeding

### ISSUE THREAD

**Issue by myunggeonchung** [google-pay/flutter-plugin#119]
I embeded the pay plugin into a flutter code to use apple pay and google pay.
When a tester attempts to use the google pay, he faced the error as below.
![스크린샷 2022-02-21 오후 9 08 58](https://user-images.githubusercontent.com/54304539/154953177-35a45f49-e9df-488d-a966-69dc3389706d.png)

This is the json file that the app load for GooglePay.
{
  "provider": "google_pay",
  "data": {
    "environment": "TEST",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "example",
            "gatewayMerchantId": "gatewayMerchantId"
          }
        },
        "parameters": {
          "allowedCardNetworks": ["VISA", "MASTERCARD", "AMEX", "JCB"],
          "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
          "billingAddressRequired": true,
          "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": true
          }
        }
      }
    ],
    "transactionInfo": {
      "countryCode": "US",
      "currencyCode": "USD"
    }
  }
}
 
How can I fix the issue?

**Comment by myunggeonchung** [comment]
I fixed it so I closed

**Comment by ravilimbani2203** [comment]
> I fixed it so I closed

How can you fix this?

**Comment by Shilpa26v** [comment]
Hii ,
i am not getting does we need to implement any other in app module to make live app.
what will be exactly there in gateway and gatewaysmerchant id?
can you please explain this?

**Comment by Shilpa26v** [comment]
> I fixed it so I closed

can you please let me know how this will work?
