### ISSUE TITLE
Unsupported version of Google play billing 

### ISSUE THREAD

**Issue by itsdani121** [google-pay/flutter-plugin#120]
Hi i am using pay:1.0.8 version in my app which i want to integrate for payment purposes so after that when i set payment method and try to upload app on play console then i did not do this due to this error which i got. i dont know what is happening?

![image](https://user-images.githubusercontent.com/30481834/155830694-1b8720ba-968c-46fd-bde8-401eda7a8edd.png)

**Comment by JlUgia** [comment]
Hi @itsdani121, [Google Pay](https://g.co/pay/api) and [Google Play Billing](https://developer.android.com/google/play/billing) are two separate offerings. You can use Google Pay for physical goods and Google Play billing for in-app digital resources.
The error you see is related to Google Play Billing. Take a look at the [play billing docs (see the latest version available)](https://developer.android.com/google/play/billing/integrate#dependency).
