### ISSUE TITLE
Add Amazon Payment Service (Pay Fort) payment provider

### ISSUE THREAD

**Issue by predatorx7** [google-pay/flutter-plugin#122]
Can we add Amazon's Pay Fort as a new payment provider in the plugins?

I can try to make separate payfort_android & payfort_ios plugins that implements [google-pay/flutter-plugin/pay_platform_interface](https://github.com/google-pay/flutter-plugin/tree/main/pay_platform_interface). 

Is unendorsed support possible? because `google-pay/flutter-plugin/tree/main/pay_platform_interface` has interfaces and enum [`PayProvider` enum](https://github.com/google-pay/flutter-plugin/blob/main/pay_platform_interface/lib/core/payment_configuration.dart#L20) only for Google Pay and Apple pay.

**Comment by JlUgia** [comment]
Hello @predatorx7.
Payfort is a payment provider that, in turn, can be used with Apple Pay (see [Apple Pay's list of supported payment providers](https://developer.apple.com/apple-pay/payment-platforms/)). This plugin does not intend to expose the integration of concrete PSPs, but instead do so under payment providers like Google Pay and Apple Pay (and others in the future).

These payment facilitators can then use their preferred payment service provider to process payments. See the list of supported payment processors for [Apple Pay](https://developer.apple.com/apple-pay/payment-platforms/) and [Google Pay](g.co/pay/processors).
