### ISSUE TITLE
Google Pay Request failed An unexpected error has occurred Please try again later [R_BIBED_07] errors

### ISSUE THREAD

**Issue by vikrantbhave08** [google-pay/flutter-plugin#123]
flutter_stripe: ^2.2.0
pay: ^1.0.8

pay.GooglePayButton(
                  paymentConfigurationAsset: 'google_pay_payment_profile.json',
                  paymentItems: _paymentItems,
                  width: 300,
                  style: pay.GooglePayButtonStyle.black,
                  type: pay.GooglePayButtonType.pay,
                  margin: const EdgeInsets.only(top: 15.0),
                  onPaymentResult: onGooglePayResult,
                  loadingIndicator: const Center(
                    child: CircularProgressIndicator(),
                  ),
                ),

{
  "provider": "google_pay",
  "data": {
    "environment": "PRODUCTION",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2020-08-27",
            "stripe:publishableKey": ""
          }
        },
        "parameters": {
          "allowedCardNetworks": ["AMEX", "DISCOVER", "INTERAC", "JCB", "MASTERCARD", "VISA"],
          "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
          "billingAddressRequired": false,
          "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": false
          }
        }
      }
    ],
    "merchantInfo": {
      "merchantId": "project@gmail.com",
      "merchantName": "KABAT"
    },
    "transactionInfo": {
      "totalPriceStatus": "FINAL",
      "totalPrice": "12.34",
      "currencyCode": "AED"
    }

  }
}

**Comment by expertdev-designer** [comment]
I also get the same issue @RedBrogdon @domesticmouse @vikrantbhave08 ..if you find any solution please let me know.
Thanks

**Comment by JlUgia** [comment]
Hi @vikrantbhave08 and @expertdev-designer.
This error indicates that your merchant configuration is invalid.

Looking at the configuration above, you are setting the `environment` to production and your `merchantId` does not contain a valid identifier. You can obtain an identifier on [Google Pay's Business Console](pay.google.com/business/console), and request access to production for the Google Pay APIs.
In the meantime, you can test your integration using the `"TEST`" environment.

**Comment by expertdev-designer** [comment]
Hii @JlUgia I checked my merchantid is correct and but everything is fine ..google sheet is open and processing the transaction but the transaction doesn't deduct from my bank. 

I checked the whole process in the signed apk.
Please help

**Comment by JlUgia** [comment]
Note that Google Pay does not process your payment.
To do that, you need to send the resulting payment token to your PSP (if your config is up to date, it seems that this is Stripe).

Take a look at a [sample gist](https://github.com/google-pay/pay-server-demos/blob/main/google-pay-psp-client/handlers/stripe.js) about how to do that with Stripe, or review the [documentation for Google Pay in Stripe](https://stripe.com/docs/google-pay).

**Comment by philipscott** [comment]
Hi, I am experiencing the same issue. My test processes perfectly and I can see the results in the Stripe payments log, however when I switch to live then I get this same error. ANY suggestions would be much appreciated it. I don't see any logs in Stripe that in the production environment that google made any calls to stripe, however in test I can see the calls. The app has been approved by Google Pay (albeit an earlier version that used a different stripe plugin.). I have tried with and without that PAY plugin and I get exactly the same error.

**Comment by dream78671** [comment]
> Hi @vikrantbhave08 and @expertdev-designer. This error indicates that your merchant configuration is invalid.
> 
> Looking at the configuration above, you are setting the `environment` to production and your `merchantId` does not contain a valid identifier. You can obtain an identifier on [Google Pay's Business Console](https://pay.google.com/business/console), and request access to production for the Google Pay APIs. In the meantime, you can test your integration using the `"TEST`" environment.

just a quick question - how do you request  access to production for google pay in order to live payments ? 
I have setup the Google Pay's Business Console but its say that 
```

Integrate with your Android app
There are no Android apps currently associated with {email address} as the account owner, admin, or user. To take action, you must be in one of those roles.
```

**### So how do i that  ?** 
upload the app on google play console and then it can recognized the app package ??
