### ISSUE TITLE
Flutter 3.0 : Execution failed for task ':pay_android:compileDebugKotlin'.

### ISSUE THREAD

**Issue by amit-flutter** [google-pay/flutter-plugin#131]
```
e: /Users/karmaln/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.6/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (50, 69): Type mismatch: inferred type is Activity? but Activity was expected
e: /Users/karmaln/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.6/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (69, 74): Type mismatch: inferred type is String? but String was expected
e: /Users/karmaln/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.6/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (73, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Map<String, Any>?
e: /Users/karmaln/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.6/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (74, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Map<String, Any>?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pay_android:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1

```

```
in android/build.gradle

dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

in app/build.gradle
compileSdkVersion 31
minSdkVersion 21

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.gms:play-services-wallet:19.1.0'
}

in androidMainfest.xml
<meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            android:value="true" />
```

**Comment by edlea** [comment]
For anyone else finding this, https://github.com/google-pay/flutter-plugin/issues/126#issuecomment-1125747859 fix the issue for me

**Comment by pranavo72bex** [comment]
> For anyone else finding this, [#126 (comment)](https://github.com/google-pay/flutter-plugin/issues/126#issuecomment-1125747859) fix the issue for me

solution did not work for me

**Comment by tudor07** [comment]
Same problem for me

**Comment by pranavo72bex** [comment]
> Same problem for me

wait for this pr get merge https://github.com/google-pay/flutter-plugin/pull/129

**Comment by matthewfx** [comment]
When can we expect a release with that issue fixed?

**Comment by JlUgia** [comment]
`pay: 1.0.9` and `pay_android: 1.0.7` are now published, addressing this issue.
Thank you.

**Comment by mhdabdellah** [comment]
Launching lib\main.dart on SM M022G in debug mode...
lib\main.dart:1
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter_helper-0.3.1\android\src\main\kotlin\com\tfliteflutter\tflite_flutter_helper\TfliteFlutterHelperPlugin.kt: (43, 1): Class 'TfliteFlutterHelperPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter_helper-0.3.1\android\src\main\kotlin\com\tfliteflutter\tflite_flutter_helper\TfliteFlutterHelperPlugin.kt: (143, 2): 'onRequestPermissionsResult' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tflite_flutter_helper:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
Exception: Gradle task assembleDebug failed with exit code 1


**any one can help me please ?
 I have an error  with tflite_flutter_helper
i use it to pre-processr images  **

**Comment by TanuJain2002** [comment]
Getting the same error .Whats the solution
