### ISSUE TITLE
ios not charged account

### ISSUE THREAD

**Issue by devmfouad** [google-pay/flutter-plugin#133]
all steps to implement apple pay in my flutter app done
and the payment success 
but the main problem is user not charged 
the connect to real merchant id and developer account
hope find solution and help
thanks

**Comment by JlUgia** [comment]
Hello @devmfouad, not that Apple Pay and Google Pay do not process the payment, but rather shared payment details securely with your payment processor. You still need to integrate with your processor of choice to create payment transactions. 

Take a look at the list of [supported payment platforms on Apple Pay](https://developer.apple.com/apple-pay/payment-platforms/) and the [participating processors on Google Pay](https://g.co/pay/processors).
