### ISSUE TITLE
Continue button not working in Android

### ISSUE THREAD

**Issue by SivaKumarViOS** [google-pay/flutter-plugin#134]
I have completed the integration a month before. The Google Pay in Android and Apple Pay in iOS was working fine in Production mode. But recently when Im checking google pay in Android with the Same build Im facing error.

Issue scenario:
When I click Order with G Pay button , A page open with the Gmail credential and the Card details added in Pay app. The continue button in that page is not working. When I click on the Continue button No action is happening.

Note: But the Same code is worked fine last month. Recently I'm facing this issue.

I have attached screenshot for the reference. Please help me to resolve this issue. Thanks

![IMG_3946](https://user-images.githubusercontent.com/106302357/170440301-c086c1ce-d829-4064-b498-b4e0e3fdac59.JPG)

**Comment by JlUgia** [comment]
Hi @SivaKumarViOS, does this issue persist?
What happens to the payments UI when you click the button, does it hide, or stay in screen?

**Comment by JlUgia** [comment]
Hi @SivaKumarViOS , I'm closing this issue if there are no additional updates.
Feel free to re-open otherwise.

**Comment by evgenyh** [comment]
same issue. it just stays the same,

**Comment by deltaxsingh** [comment]
This is happening across apps, it must be a Google wallet issue. 

Typical Google, they don't use their own products and only have bots responding to support requests by people. They won't figure out this big for another couple of months or years.
