### ISSUE TITLE
Can't change country and No credits cards shown 

### ISSUE THREAD

**Issue by MezoPeeta** [google-pay/flutter-plugin#136]
I've a credit card on my Google pay but it doesn't show it to me it leads me to add a new card and when I card that it exists it doesn't allow besides I can't change the country It's stick on United States and no errors are shown

**Comment by JlUgia** [comment]
Hi @MezoPeeta, what type of card do you have in your account?
Also, how does your payment configuration looks like? Remember that the card types that you don't include in the configuration won't show up in the payments sheet.

**Comment by JlUgia** [comment]
Hi @MezoPeeta, your configuration looks good.
What country are you operating from?
Have you tried using a less restrictive configuration (eg.: removing the `billingAddressRequired` and `billingAddressParameters` properties, and including [all the allowed values in  `allowedCardNetworks`](https://developers.google.com/pay/api/web/reference/request-objects))?
What do you mean when you say that you can't change countries?

**Comment by ndesamuelmbah** [comment]
One thing        I do not understand from the documentation is this.

When we specify transactionInfo property of the payment method as shown below.

``` 
"transactionInfo": {
      "countryCode": "US",
      "currencyCode": "USD"
}
```

What exactly does this mean? Are we saying that all transactions will be processed in USD or in the United States? 

@MezoPeeta   do you think this is why the country code is stock to US?
