### ISSUE TITLE
Payment not completed error in Apple Pay

### ISSUE THREAD

**Issue by jacobokoenig** [google-pay/flutter-plugin#140]
Hi, I am getting a "Payment not completed" error when using a US and USD in the configuration. My issue is that when the payment sheet fails, I get no details of the error. I tried both with Pay's button and Advanced usage, but have found no way to retrieve the error.

Can someone point me on the right direction?

**Comment by JlUgia** [comment]
Hi @jacobokoenig, can you share your configuration (only public details –eg.: removing any account ids and secrets) to understand the root of the failure?

Note that the button has an `onError` property that you can use to inspect the issue. In the advanced usage, [calling the `showPaymentSelector` method will except with an error](https://github.com/google-pay/flutter-plugin/blob/ad1bd7252659f4c07598d69cc2aa683f424c5d36/pay/lib/src/widgets/pay_button.dart#L76) if the operation fails.

**Comment by JlUgia** [comment]
Hi @jacobokoenig, I'm closing this issue if there are no additional updates.
Feel free to re-open otherwise.
