### ISSUE TITLE
Flutter on iOS: redefinition of module 'Firebase'

### ISSUE THREAD

**Issue by kenaitian** [google-pay/flutter-plugin#145]
Error received after executing "flutter run ios":

logs can found via [ios_logs_flutter_run](https://github.com/lessimp/lessimp_logs/blob/main/ios_logs_flutter_run) and [ios_logs_flutter_run_-v](https://github.com/lessimp/lessimp_logs/blob/main/ios_logs_flutter_run_-v)

Note: pay_ios related issues were previously addressed here before Flutter version 3.5 and even when I "git checkout 3.0.0" for flutter version:
1. https://github.com/google-pay/flutter-plugin/issues/135
2. https://github.com/actions/virtual-environments/issues/5469

**Comment by kenaitian** [comment]
This did help to resolve the issues outlined in the logs: https://stackoverflow.com/questions/70760326/flutter-on-ios-redefinition-of-module-firebase

Yet, this error follows:

Launching lib/main.dart on iPhone (3) in debug mode...
Updating project for Xcode compatibility.
Upgrading Runner.xcscheme
Automatically signing iOS for device deployment using specified development team in Xcode project: SJAV7HZQZ6
Running Xcode build...
Xcode build done.                                           1731.4s
Installing and launching...
(lldb) 2022-07-18 20:49:21.714199-0400 Runner[32111:1149425] 9.2.0 - [FirebaseCore][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
9.2.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
9.2.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
No windows have a root view controller, cannot save application state
Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 59511
This was attempt #50. Will retry in 0:00:01.600000.

**Comment by JlUgia** [comment]
Hi @kenaitian This issue doesn't seem related to this plugin. I'd suggest posting this issue within Firebase domains.
