### ISSUE TITLE
Apple pay success is not showing in stripe

### ISSUE THREAD

**Issue by JValderramaN** [google-pay/flutter-plugin#147]
Hi!

thank you for this plugin, is awesome.

We have an app that uses stripe as payment gateway. after configuring everything, i don't see anything that "binds" stripe to apple pay, maybe is something missing? 

the thing is: we receive the success callback, and save the response in our backend side. But the payment is not showing in stripe dashboard (??), is not showing in the bank account and is not showing in apple wallet history ([maybe this is another issue with iOS..](https://www.reddit.com/r/AppleCard/comments/o0hsga/recent_transactions_not_showing_up/)). We contacted stripe support, they say if we use a plugin outside their documentation, we need to reach the plugin owner :)

Could you please let us know what is missing? I've attached the configuration files for apple pay. Note also the google pay (in this case we are just testing apple..), which it does contains some stripe metadata (like stripe:publishableKey), we need something similar in apple?

--- content of apple_pay.json ---
`{
  "provider": "apple_pay",
  "data": {
    "merchantIdentifier": "someID..",
    "displayName": "Click&Correct",
    "merchantCapabilities": [
      "3DS",
      "debit",
      "credit"
    ],
    "supportedNetworks": [
      "amex",
      "visa",
      "discover",
      "masterCard"
    ],
    "countryCode": "FR",
    "currencyCode": "EUR",
    "requiredBillingContactFields": ["postalAddress"],
    "requiredShippingContactFields": []
  }
}`

--- content of google_pay.json ---

`{
  "provider": "google_pay",
  "data": {
    "environment": "PRODUCTION",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2018-10-31",
            "stripe:publishableKey": "pk_live_blablabla"
          }
        },
        "parameters": {
          "allowedCardNetworks": [
            "VISA",
            "MASTERCARD"
          ],
          "allowedAuthMethods": [
            "PAN_ONLY",
            "CRYPTOGRAM_3DS"
          ],
          "billingAddressRequired": true,
          "billingAddressParameters": {
            "format": "FULL"
          }
        }
      }
    ],
    "merchantInfo": {
      "merchantId": "someID..",
      "merchantName": "Click&Correct"
    },
    "transactionInfo": {
      "countryCode": "FR",
      "currencyCode": "EUR"
    }
  }
}`

hope we can find a solution,
thanks in advance

**Comment by JlUgia** [comment]
Hello @JValderramaN, at the moment this repo does not include samples or information about what to do with the payment tokens emitted by the payment providers (eg.: Apple Pay). If you think such samples can be useful, feel free to start a feature request/poll/idea in the discussions section.

The community has produced an open source plugin for Stripe that contains an [example of how to use this plug-in with Stripe](https://github.com/flutter-stripe/flutter_stripe/blob/2ae832a6b25b331616f6344efbe19d5c982cd89e/example/lib/screens/wallets/apple_pay_screen_plugin.dart#L70) once the result from the `pay` plugin is received. Let me know if that's not what you are looking for.

**Comment by JValderramaN** [comment]
Hi @JlUgia  thanks for the reply (sorry for delay). This week I could finish the integration with flutter stripe and apple pay. The magic trick was creating the apple merchant certificate from the stripe certificate-signing, following their guidelines.

Best regards
