### ISSUE TITLE
i wants to go for UPI payment in production mode using pay: ^1.0.11

### ISSUE THREAD

**Issue by Sudesh101999** [google-pay/flutter-plugin#154]
in my google_pay.json file i have implemented. but this is test mode only and for card payment. i have to make payment with UPI in production mode. so where and what i have to change. i already have created google pay merchant id. but not able to get that where and what i have to add my merchant id and name.

```
{
  "apiVersion": 2,
  "apiVersionMinor": 0,
  "merchantInfo": {
    "merchantName": "Example Merchant"
  },
  "allowedPaymentMethods": [
    {
      "type": "CARD",
      "parameters": {
        "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
        "allowedCardNetworks": ["AMEX", "DISCOVER", "INTERAC", "JCB", "MASTERCARD", "MIR", "VISA"]
      },
      "tokenizationSpecification": {
        "type": "PAYMENT_GATEWAY",
        "parameters": {
          "gateway": "example",
          "gatewayMerchantId": "exampleGatewayMerchantId"
        }
      }
    }
  ],
  "transactionInfo": {
    "totalPriceStatus": "FINAL",
    "totalPrice": "12.34",
    "currencyCode": "USD"
  }
}
```

Thank you.

**Comment by JlUgia** [comment]
Hi @Sudesh101999, this plugin uses the [Google Pay SDK for Android](g.co/pay/api), which does not support UPI. Take a look at [this issue](https://github.com/google-pay/flutter-plugin/issues/33) where alternatives to collect payments using UPI are discussed.

**Comment by Sudesh101999** [comment]
Thank your @JlUgia for reply.  For android "android_intent: ^2.0.2" is DISCONTINUED in india as i can see
![image](https://user-images.githubusercontent.com/85933639/190154709-777d00df-7112-4347-9c52-bf84003ae9d4.png)

any other options is there for android. Actully i'm working on this last 3 days but i just failded for UPI transection. so i just asked on here. is there any another way for UPI payment in Flutter project.
