### ISSUE TITLE
Payment is not made

### ISSUE THREAD

**Issue by osamamohammed98** [google-pay/flutter-plugin#156]
I have done the required settings as shown in your document for Apple, but when I pay with the system’s bottom sheet choose the card and make the payment, the process is completed successfully, but the amount is not deducted and the reports are not shown in the developer account. I will attach pictures of my code to you

pay: ^1.0.11

<img width="699" alt="Screen Shot 2022-10-03 at 10 42 45 AM" src="https://user-images.githubusercontent.com/27555246/193525546-6ea0b304-d9de-412f-8762-cc9c3b8c86f5.png">

<img width="469" alt="Screen Shot 2022-10-03 at 10 45 26 AM" src="https://user-images.githubusercontent.com/27555246/193525671-6b88882c-4ba7-4ab5-9323-b009a84af037.png">

<img width="1041" alt="Screen Shot 2022-10-03 at 10 46 06 AM" src="https://user-images.githubusercontent.com/27555246/193525770-d32382e9-67c7-4125-aed4-f5c588f62598.png">

response

<img width="575" alt="Screen Shot 2022-10-03 at 10 47 55 AM" src="https://user-images.githubusercontent.com/27555246/193526101-588aaef8-b2f6-4fef-9e90-98593b83d2c6.png">

<img width="1512" alt="Screen Shot 2022-10-03 at 10 49 08 AM" src="https://user-images.githubusercontent.com/27555246/193526356-a7c80d3f-8226-476b-986f-64b4aebd5acf.png">

**Comment by JlUgia** [comment]
Hi @osamamohammed98, Apple Pay on iOS does not process any payments. To make a payment you need a payment service provider (ie.: PSP). You can find a [list of supported PSPs for Apple Pay in the following link](https://developer.apple.com/apple-pay/payment-platforms/).

The final step of sending the encrypted payment method you selected using Apple Pay will depend on the PSP you use. Most of the times, it'll require receiving the selected payment method information in your backend and sharing it with your PSP.
To make the integration easier, we have prepared [a repository with samples for some of the most popular PSPs](https://github.com/google-pay/pay-server-demos).
Let me know if this helps.

**Comment by osamamohammed98** [comment]
> Hi @osamamohammed98, Apple Pay on iOS does not process any payments. To make a payment you need a payment service provider (ie.: PSP). You can find a [list of supported PSPs for Apple Pay in the following link](https://developer.apple.com/apple-pay/payment-platforms/).
> 
> The final step of sending the encrypted payment method you selected using Apple Pay will depend on the PSP you use. Most of the times, it'll require receiving the selected payment method information in your backend and sharing it with your PSP. To make the integration easier, we have prepared [a repository with samples for some of the most popular PSPs](https://github.com/google-pay/pay-server-demos). Let me know if this helps.

the example not The example is not useful

**Comment by JlUgia** [comment]
Hey @osamamohammed98, my recommendation is to take a look at the resources provided by the payment service provider you are using in your application, and look for documentation where they describe how to send the encrypted payload received from Apple Pay or Google Pay to create an order.

**Comment by osamamohammed98** [comment]
It is true that this is done through the native, but in the flutter of how to do this after searching, it turns out that in iOS the whole process is done by the system, so why not do this in your library, especially since the code is simple, but I cannot implement it in the method channel

**Comment by osamamohammed98** [comment]
Or if you can provide an API for this step because your library is very flexible and easy and this feature will make it the best ever

**Comment by JlUgia** [comment]
Hey @osamamohammed98 what do you mean with "in iOS the whole process is done by the system". Do you have documentation about that?
AFAIK, Apple Pay simply returns the payment method back to you, and you are responsible to forward that to your PSP. What PSP are you using to process payments?
