### ISSUE TITLE
White google pay button?

### ISSUE THREAD

**Issue by KestasVenslauskas** [google-pay/flutter-plugin#158]
Why there is no way to set a white style for a google pay button?

**Comment by JlUgia** [comment]
Hi @KestasVenslauskas, the new Google Pay button is only available in one color. Take a look at the [brand guidelines](https://developers.google.com/pay/api/android/guides/brand-guidelines#style) to learn more.
Does that style work with your UI? We are certainly happy to receive feedback about your concrete use case.

**Comment by GuimG** [comment]
Hey @JlUgia if you check the brand guidelines again you'll see how they've added the white button. I got my app rejected for that. Could this issue be reconsidered?
