### ISSUE TITLE
Is it possible to dev test without payment gateway provider?

### ISSUE THREAD

**Issue by KestasVenslauskas** [google-pay/flutter-plugin#159]
Basically what title says. I wonder if there is a possability to make a test payment without setting actual payment gateway provider details?

**Comment by JlUgia** [comment]
Hello @KestasVenslauskas, Google Pay does not process payments by itself. You can use it in conjunction with either a payment gateway or a your own payments processing system/backend. So to perform an actual payment in test mode you'd need any of the two.

That said, Google Pay can also operate in `TEST` mode, so you can see how the flow looks like and feels before using it in `PRODUCTION`, although keep in mind that this does not include any actual payment transaction.

Let me know if this helps.

**Comment by KestasVenslauskas** [comment]
@JlUgia So right now I dont have any payment gateway selected but I do try this in `TEST` mode. `TEST` mode also requires us to have a payment gateway configuration setup yes?

**Comment by JlUgia** [comment]
You can test your integration in `TEST` mode *without* a configuration for your payment provider.

**Comment by KestasVenslauskas** [comment]
@JlUgia Thank you! I checked exampe app and it worked. While in our application I always got "DeveloperErrorException" without any details. The reason was I had to remove `MAESTRO` from `allowedCardNetworks` config.
