### ISSUE TITLE
payment not completed in real device with Apple Pay

### ISSUE THREAD

**Issue by El-sayed-mahmoud** [google-pay/flutter-plugin#163]
<img width="425" alt="Screen Shot 2022-10-18 at 3 49 06 PM" src="https://user-images.githubusercontent.com/44328427/196460268-9ca2730a-f79b-48d7-9d6e-05f6c9368569.png">

**Comment by JlUgia** [comment]
Do you have more details about possible causes of the error (like your Apple Pay configuration, or your integration details)?

**Comment by JlUgia** [comment]
Hi @El-sayed-mahmoud , I'm closing this issue if there are no additional updates.
Feel free to re-open otherwise.
