### ISSUE TITLE
Unhandled Exception: PlatformException(10, , null, null) when press google pay flutter

### ISSUE THREAD

**Issue by rahafff** [google-pay/flutter-plugin#164]
when pressing the google pay button, I call the showPaymentSelector method  but I get this error 
`E/flutter ( 4453): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(10, , null, null)
E/flutter ( 4453): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter ( 4453): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
E/flutter ( 4453): <asynchronous suspension>
E/flutter ( 4453): #2      PayMethodChannel.showPaymentSelector (package:pay_platform_interface/pay_channel.dart:64)
E/flutter ( 4453): <asynchronous suspension>
E/flutter ( 4453): #3      _PaySampleAppState.onGooglePayPressed (package:cater_me_v2/flutter_pay_test.dart:585)
E/flutter ( 4453): <asynchronous suspension>`

**Comment by JlUgia** [comment]
This seems like an error in your configuration JSON. Can you share your configuration omitting any secret values?

**Comment by oremlawi** [comment]
I'm getting the same issue only for Google Pay when I click "GPay" button, and here are the configurations I have:

`final String defaultGooglePay = '''{
  "provider": "google_pay",
  "data": {
    "environment": "PRODUCTION",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [{
      "type": "CARD",
      "tokenizationSpecification": {
        "type": "PAYMENT_GATEWAY",
        "parameters": {
          "gateway": "password",
          "gatewayMerchantId": "AAAAAAAAAAAAAAA"
        }
      },
      "parameters": {
        "allowedCardNetworks": ["VISA", "MASTERCARD", "AMEX"],
        "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
        "billingAddressRequired": false
      }
    }],
    "merchantInfo": {
      "merchantId": "23423424234324",
      "merchantName": "App_Name"
    },
    "transactionInfo": {
      "countryCode": "QA",
      "currencyCode": "QAR"
    }
  }
}''';
`

And I call them like this:
`Pay _payClient = Pay({
      PayProvider.google_pay: PaymentConfiguration.fromJsonString(
          payment_configurations.defaultGooglePay),
      PayProvider.apple_pay: PaymentConfiguration.fromJsonString(
          payment_configurations.defaultApplePay),
    });`

Apple Pay is working fine, but not for Google Pay, any idea?

**Comment by dvohl** [comment]
Same issue for me.
`Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22000.1696], locale de-DE)`
and 'pay' Version 1.1.0. Also tried version 1.0.10. Same issue.

I got it working 2-3 times in the last 8 hours. But when hot-reloading or restarting the app, it's the same error again.
I'm using the same physical device for testing, that I use with other GPay apps created by me. Copied configurations, tripple checked code and configs... I don't know why this error happens most of the time.

**Comment by dvohl** [comment]
I found the issue and it's a simple solution:
The PaymentItem is not properly set. In my case the label and amount attribute were somehow null. 
Need to check my Rest-API now. Working with fixed values works fine as it should.

I guess there should definitly be a proper exception message than PlatformException(10, , null, null).
