### ISSUE TITLE
can't decode onApplePayResult dynamic value

### ISSUE THREAD

**Issue by heshesh2010** [google-pay/flutter-plugin#166]
Hi , my apple pay button works great and return the token but i just need these values from onApplePayResult :

    transactionId,
    ephemeralPublicKey,
    publicKeyHash,
    data,
    signature,
    version,
    transactionIdentifier,
    network,
    displayName,
    type,

i'm using this code 

  void onApplePayResult(paymentResult) {

    if (paymentResult is String) {
      Fluttertoast.showToast(
          msg: "String",
          toastLength: Toast.LENGTH_LONG,
          gravity: ToastGravity.TOP);
    }

    if (paymentResult is Map) {
      Fluttertoast.showToast(
          msg: "map",
          toastLength: Toast.LENGTH_LONG,
          gravity: ToastGravity.TOP);
    }

    Map result = jsonDecode(paymentResult); // give me error 

    //  String transactionIdentifier = jsonDecode(paymentResult["transactionIdentifier"]);

    String network = result['token']['network'];
    String displayName = result['token']['displayName'];
    String type = result['token']['type'].toString();

    String version = result['token']['version'].toString();
    String data = result['token']['data'];
    String signature = result['token']['signature'];
    String ephemeralPublicKey = result['header']['ephemeralPublicKey'];
    String publicKeyHash = result['header']['publicKeyHash'];
    String transactionId = result['header']['transactionId'].toString();

    
  }

**Comment by JlUgia** [comment]
Hi @heshesh2010, this is a sample response for an Apple Pay payment attempt:

```json
{
  "billingContact": {
    "name": {
      "nameSuffix": "",
      "phoneticRepresentation": {
        "nickname": null,
        "givenName": "",
        "namePrefix": null,
        "familyName": "",
        "middleName": "",
        "phoneticRepresentation": null,
        "nameSuffix": null,
      },
      "nickname": "",
      "familyName": "Ugia",
      "givenName": "Jose",
      "namePrefix": "",
      "middleName": "",
    },
    "postalAddress": {
      "postalCode": "00000",
      "subAdministrativeArea": "",
      "city": "Seattle",
      "subLocality": "",
      "street": "Calle del Àrbol",
      "country": "Macedonia",
      "state": "Andes",
      "isoCountryCode": "ES",
    },
  },
  "transactionIdentifier": "Simulated Identifier",
  "token": "",
  "paymentMethod": {
    "displayName": "Simulated Instrument",
    "network": "AmEx",
    "type": 0
  },
}
```

You don't need to decode the `paymentResult` which is a `Map` already, hence you can do the following:
```dart
final String transactionIdentifier = paymentResult["transactionIdentifier"];

final Map paymentMethod = paymentResult['paymentMethod'];
final String network = paymentResult['network'];
final String displayName = paymentResult['displayName'];
final String type = paymentResult['type'].toString();

final Map tokenData = jsonDecode(paymentResult['token'])['paymentData']
final String version = tokenData['version'].toString();
final String data = tokenData['data'];
final String signature = tokenData['signature'];

final Map header = tokenData['header'];
final String ephemeralPublicKey = header['ephemeralPublicKey'];
final String publicKeyHash = header['publicKeyHash'];
final String transactionId = header['transactionId'].toString();
```
