### ISSUE TITLE
Flutter pay with flutter_stripe giving error OR_BIBED_08 on android

### ISSUE THREAD

**Issue by rahul-devronins** [google-pay/flutter-plugin#167]
Following is the json:
`{
  "provider": "google_pay",
  "data": {
    "environment": "TEST",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2020-08-27",
            "stripe:publishableKey": "pk_test_g6Z9AJHLhNewb5GMxZcGXLvQ"
          }
        },
        "parameters": {
          "allowedCardNetworks": ["VISA", "MASTERCARD"],
          "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
          "billingAddressRequired": true,
          "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": true
          }
        }
      }
    ],
    "merchantInfo": {
      "merchantId": "<MyAppMerchantId>",
      "merchantName": "MyAppName"
    },
    "transactionInfo": {
      "countryCode": "US",
      "currencyCode": "USD"
    }
  }
}`

Error is:
![Screenshot_20221101_133123](https://user-images.githubusercontent.com/74700174/199186745-70cc2f8b-63c6-447c-9813-d8ba19a3af89.png)

**Comment by JlUgia** [comment]
Hi @rahul-devronins, using your PSP configuration has no effect in the `TEST` environment (and it seems to be creating a conflict for you). Using the sample `gateway: example` in your configuration should let you test your integration before going to production.

**Comment by JlUgia** [comment]
Hi @rahul-devronins, I'm closing this issue if there are no additional updates.
Feel free to re-open otherwise.
