### ISSUE TITLE
Is this plugin enough to make payment with Braintree?

### ISSUE THREAD

**Issue by KestasVenslauskas** [google-pay/flutter-plugin#170]
I'm trying to integrate Braintree payments into my app but I just always get "OR_BIBED_07" error.
I can't seem to find any example implementing this with BrainTree and I start wondering maybe I'm on the wrong path using this plugin.

Error from android console:
`... E Volley  : [863] ekb.b: Unexpected response code 500 for https://payments-pa.googleapis.com/payments/apis-secure/ui2/buyflowservice/initialize`

**Comment by JlUgia** [comment]
Good day @KestasVenslauskas.
I'm closing the issue assuming that the previous answer addresses your question.
Feel free to re-open otherwise.
