### ISSUE TITLE
Modify style of pay button

### ISSUE THREAD

**Issue by jeruilo** [google-pay/flutter-plugin#174]
Good afternoon, 
I have more a question than an issue, it's about the style of the button. I'm trying to get some design similar to the bottom one, but the first button is the closest I'm. 

Any help/tip would be appreciated, thanks in advance!
<img width="159" alt="image" src="https://user-images.githubusercontent.com/108392890/206179417-9ee9c537-c689-48b9-a95c-3e5a8a7d4d33.png">

**Comment by JlUgia** [comment]
Hey @jeruilo, the Google Pay button is only available with a dark background at the moment. Take a look at the [design guidelines](https://developers.google.com/pay/api/android/guides/brand-guidelines) to learn more.

**Comment by jeruilo** [comment]
Thank you @JlUgia , have a nice day!
