### ISSUE TITLE
Payment configuration security

### ISSUE THREAD

**Issue by artemsorochan** [google-pay/flutter-plugin#175]
As mentioned in doc(https://github.com/google-pay/flutter-plugin/tree/main/pay#payment-configuration) we may use local file for payment configuration. Is it ok to set google/apple pay merchant id in local file(is it ok to be public)?

**Comment by JlUgia** [comment]
In principle, merchant identifiers are not secret values, so you can include them in your source code. That said, I can confirm with you on the Google Pay end and look for confirmation on Apple Pay's end too /cc @jkboch

**Comment by JlUgia** [comment]
Confirming that Google Pay's merchant ids are not considered secret values.
