### ISSUE TITLE
The button doesn't appears on phones 

### ISSUE THREAD

**Issue by iUnknownWs** [google-pay/flutter-plugin#176]
I´m trying to integrate google pay but the button doesn't appears, i create another project to test and this is the error i got.

in the emulator the button at least appears but in my phone not.

Edit: I just discover that in emulator with API 30 doesn't work but 31 and 33 it does. i tested it in two difference phone and the button still doesn't show up

debugging the app in my phone i got this:

```
W/Activity(27610): PerfMonitor: Slow Operation: Activity com.example.gpay/.MainActivity onDestroy took 202ms
D/AppScoutStateMachine(27610): 27610-ScoutStateMachinecreated
D/DecorView[](27610): getWindowModeFromSystem  windowmode is 1
D/SurfaceView(27610): UPDATE null, mIsCastMode = false
D/SurfaceView(27610): UPDATE Surface(name=SurfaceView[com.example.gpay/com.example.gpay.MainActivity])/@0xffd4333, mIsProjectionMode = false
D/SurfaceControl(27610): nativeSetScreenProjection ===> setScreenProjection

```
```
GooglePayButton(
              paymentConfigurationAsset:
                  'default_payment_profile_google_pay.json',
              paymentItems: _paymentItems,
              type: GooglePayButtonType.pay,
              margin: const EdgeInsets.only(top: 15.0),
              onPaymentResult: print,
              loadingIndicator: const Center(
                child: CircularProgressIndicator(),
              ),
            ),
```

**Comment by rvharjinderbains** [comment]
Hi, @iUnknownWs, I had same issue but after following these steps I got solution:-

If the button doesn’t show in the real device:
1- make sure you have a testing account on the device.
2- When you add testing account select available country for apple pay.
3- Region in your device should be in available country for apple pay.
4- Add testing cards to (My wallet app) using [apple testing cards](https://developer.apple.com/apple-pay/sandbox-testing/).

**Comment by JlUgia** [comment]
The Google Pay integration does not have any country restrictions  in `TEST` mode, hence the reasons why you don't see the button are different. Can you confirm that:
1. You are using an Android device with Google Play services installed
2. You are logged in with a valid Google account in your device?

Take a look at the docs to learn more about the [integration requirements](https://developers.google.com/pay/api/android/guides/setup).

**Comment by JlUgia** [comment]
Assuming resolution and closing.
Feel free to re-open otherwise.
