### ISSUE TITLE
Apple Pay region 

### ISSUE THREAD

**Issue by emreebingor** [google-pay/flutter-plugin#177]
How can I set visibility for the regions? For example I don't wanna show it if it is not supported in that region? Thanks a lot

**Comment by JlUgia** [comment]
That's something that the `userCanPay` method can do for you, by returning `false` if Apple Pay is not available for a given user. Take a look at the [advanced integration path](https://pub.dev/packages/pay#advanced-usage), concretely the `PayClient.userCanPay` method, which lets you take action based on whether the payment provider in question is available or not.

In case you need additional context on how Apple Pay determines payment availability, `userCanPay` calls [`canMakePayments`](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationcontroller/1649457-canmakepayments) on the Apple Pay end.
