### ISSUE TITLE
Apple Pay Is Not Available in App - Flutter

### ISSUE THREAD

**Issue by rvharjinderbains** [google-pay/flutter-plugin#180]
I am getting bellow error in IOS device when trying to pay with Apple Pay:-

Apple Pay is Not available in "App"
Check the settings for this app and make sure it was designed to use Apple Pay.
![Screenshot 2023-01-19 at 5 48 42 PM](https://user-images.githubusercontent.com/105272009/213442095-78039d55-0fd3-4e70-a1df-55a9d6883133.png)

I am using these versions:-
Flutter SDK verison 3.3.0
pay: ^1.0.11

Please help me to solve this issue.

**Comment by JlUgia** [comment]
You probably have not completed [the integration requirements for Apple Pay](https://pub.dev/packages/pay#getting-started) yet. Is that the case?
Make sure to enable Apple Pay in your Xcode project and issue the required certificates and give it another go.
Feel free to re-open the issue if the problem persists.
