### ISSUE TITLE
GooglePayButton appearance rejected by Google for being too rounded

### ISSUE THREAD

**Issue by fergushowe** [google-pay/flutter-plugin#187]
We've had our Google Pay API integration submission rejected on the basis that "our brand guidelines have been reverted to reflect the rectangular asset and no longer the rounded Google Pay button". I attach the implementation of GooglePayButton and a screenshot showing how it appears within the app - thanks.

```
GooglePayButton(
   paymentConfiguration: PaymentConfiguration.fromJsonString(googlePayConfig),
   paymentItems: [paymentItem],
   type: GooglePayButtonType.pay,
   onPaymentResult: onGooglePayResult,
   loadingIndicator: const Center(
      child: CircularProgressIndicator(),
   ),
),
```
                          
![Screenshot_20230321-153557](https://user-images.githubusercontent.com/4727928/227248171-c65b60b8-6efe-46f4-b4a4-48d416027a1c.png)

**Comment by AliAhmad44550** [comment]
I have the same issue my app is also rejected by the Google for not matching there's brand guidelines 
![IMG_20230329_032743](https://user-images.githubusercontent.com/58605326/228380745-cbc9af0b-5046-4301-801f-a41c3488372c.jpg)

**Comment by zeeshan0080** [comment]
Please fix this issue

**Comment by alekingo** [comment]
I have the same problem. Is anyone managing to use this lib like this?

**Comment by JlUgia** [comment]
Hi @fergushowe and @alekingo, apologies for the setback.
We've taken a look and adjuster the process.
Can you confirm that this is not a publish blocker anymore?

**Comment by JlUgia** [comment]
The roundness of the button is included in the design review as valid styling.
Can you confirm the issue is resolved?
