### ISSUE TITLE
Wrong exported ApplePay json: paymentMethod: { ..., type: 1 }

### ISSUE THREAD

**Issue by oremlawi** [google-pay/flutter-plugin#188]
According to [Apple's documentation](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentmethodtype), The payment method type can be one of the following string values:

"debit"
"credit"
"prepaid"
"store"

While the received json exported by this library returns the type key as an integer `type: 1`

I had also to correct the exported key called `token` to be `paymentData`, but for the `type` key I couldn't correct it, as the mapping between card types (debit, credit, prepaid, store) and their integer equivalents are not documented anywhere.

But at least I know debit -> 1 (according to the card I was using in my test), any idea about the remaining types?

debit -> 1
credit -> ?
prepaid -> ?
store -> ?

**Comment by oremlawi** [comment]
I also added a credit card, and it returns '2'..

So apparently the mapping is like the following:

debit -> 1
credit -> 2
prepaid -> 3 (not sure)
store -> 4 (not sure)

Please confirm.

**Comment by JlUgia** [comment]
Hi @oremlawi I'm not sure I follow.
What are you referring to when you say the "JSON exported by this library"?
I also noted that the link you shared above refers to the Payment Request API integration. Note that, for the time being, this plugin only supports the iOS platform for Apple Pay. The [API for the native integration](https://developer.apple.com/documentation/passkit/apple_pay/offering_apple_pay_in_your_app) differs from the Web APIs.

**Comment by JlUgia** [comment]
Thank you for the reply @volodymyr-kam-nrtl .

This fields are currently only [JSON-deserialized before sent back](https://github.com/google-pay/flutter-plugin/blob/main/pay_ios/ios/Classes/PaymentExtensions.swift#L25) to the Flutter end.
Would you find it valuable to use a string-typed key instead?

**Comment by JlUgia** [comment]
Feel free to reopen this issue if you can add additional information.
