### ISSUE TITLE
An unexpected Error occured [OR_BFFPCPSD_01]

### ISSUE THREAD

**Issue by ShubhAppentus** [google-pay/flutter-plugin#189]
I implemented google pay in my application but i am getting an error. the error is that : " Request failed: An unexpected error occured. Please try again letter. [OR_BFFPCPSD_01]. 
I am testing google pay in Test envrionment.
Here is my Json: 
{
"apiVersion": 2,
"apiVersionMinor": 0,
"allowedPaymentMethods": [
{
"type": "CARD",
"parameters": {
"allowedAuthMethods": [
"PAN_ONLY",
"CRYPTOGRAM_3DS"
],
"allowedCardNetworks": [
"AMEX",
"DISCOVER",
"JCB",
"MASTERCARD",
"VISA"
],
"billingAddressRequired": true,
"billingAddressParameters": {
"format": "FULL"
}
},
"tokenizationSpecification": {
"type": "PAYMENT_GATEWAY",
"parameters": {
"gateway": "example",
"gatewayMerchantId": "BCSDFG2DF3HP7EJS"
}
}
}
],
"transactionInfo": {
"totalPrice": "1000",
"totalPriceStatus": "FINAL",
"countryCode": "US",
"currencyCode": "USD"
},
"merchantInfo": {
"merchantName": "example"
},
"shippingAddressParameters": {
"phoneNumberRequired": false,
"allowedCountryCodes": [
"US",
"GB"
]
},
"shippingAddressRequired": true
} 

HOW TO SOLVE THIS ERROR PLEASE HELP

**Comment by Dpp24** [comment]
Having same issue.

Is there any solution?

**Comment by ShubhAppentus** [comment]
check the solution here:- 
https://stackoverflow.com/questions/75862955/we-couldnt-complete-this-action-try-a-different-payment-method-or-contact-us?noredirect=1#comment133871510_75862955

**Comment by Dpp24** [comment]
I am using live real time card with test enviorment

it was working fine earlier
but now i got the following unxpected error

**Comment by ShubhAppentus** [comment]
You need to join [groups.google.com/g/googlepay-test-mode-stub-data](https://groups.google.com/g/googlepay-test-mode-stub-data) in order to see test cards in the payment sheet. google provide test cards for testing environment.

**Comment by Dpp24** [comment]
Thank you for your response
In demo its working fine with demo test card.

If it's all good in demo then is there any modification for live app with
live card?

**Comment by ShubhAppentus** [comment]
Before you switch to production you need to add "merchantId" and "public key" in your code and also need to verify your payflow by google.

**Comment by Dpp24** [comment]
Yeah i already added merchantId and public key into code

So my question is how to verify payflow to google
is there any steps for verification?
if then please send me

**Comment by ShubhAppentus** [comment]
okay then, you need to open google pay console https://pay.google.com/business/console/profiles . and go in google pay api tab, and clicked on manage as you seen on screenshot atteched. from there you can add all neccessory info and submit for review.
![image](https://user-images.githubusercontent.com/124139857/233365302-d8cc2c1a-e4c5-47e1-b9a7-e0ce89c354cb.png)

**Comment by Dpp24** [comment]
Yeah it will help me a lot

thank you so much for helping me
let me come back again if is there any issue comes :D
