### ISSUE TITLE
PlatformException(10, , null, null)

### ISSUE THREAD

**Issue by dvohl** [google-pay/flutter-plugin#190]
See https://github.com/google-pay/flutter-plugin/issues/164

Exception is very subtle and doesn't help at all. A better exception would help alot. Needed a few hours to find out, that my API is the problem initializing the PaymentItem.

**Comment by BaudouinCS** [comment]
You should keep this issue open @dvohl, for me it was exactly the same exception, but it was my config.json that was wrong and not the PaymentItem.
