### ISSUE TITLE
OR_BIBED_01 error occurs when I click the continue button on Goolge pay

### ISSUE THREAD

**Issue by ShubhAppentus** [google-pay/flutter-plugin#191]
i am testing it in testing envrionment but i am getting this error :

![image](https://user-images.githubusercontent.com/124139857/229693459-e34864f0-6fce-4849-8386-b104b349ac61.png)

This is my json: 

{
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
        {
            "type": "CARD",
            "parameters": {
                "allowedAuthMethods": [
                    "PAN_ONLY",
                    "CRYPTOGRAM_3DS"
                ],
                "allowedCardNetworks": [
                    "AMEX",
                    "DISCOVER",
                    "JCB",
                    "MASTERCARD",
                    "VISA"
                ],
                "billingAddressRequired": true,
                "billingAddressParameters": {
                    "format": "FULL"
                }
            },
            "tokenizationSpecification": {
                "type": "PAYMENT_GATEWAY",
                "parameters": {
                    "gateway": "example",
                    "gatewayMerchantId": "DCR2DFGGHP8JFD"
                }
            }
        }
    ],
    "transactionInfo": {
        "totalPrice": "1000",
        "totalPriceStatus": "FINAL",
        "countryCode": "US",
        "currencyCode": "USD"
    },
    "merchantInfo": {
        "merchantName": "example"
    },
    "shippingAddressParameters": {
        "phoneNumberRequired": false,
        "allowedCountryCodes": [
            "US",
            "GB"
        ]
    },
    "shippingAddressRequired": true
}

HOW I SOLVE THIS ERROR?

**Comment by JlUgia** [comment]
Your `tokenizationSpecification` contains partial TEST and PRODUCTION info.
If you are testing your integration, update your `gatewayMerchantId` to `exampleGatewayMerchantId`. See #121 and the [docs](https://developers.google.com/pay/api/android/guides/tutorial#tokenization) to learn more.

Feel free to re-open the issue if the problem persists.
