### ISSUE TITLE
Cannot trigger UPI through this Plugin.

### ISSUE THREAD

**Issue by abinvs-2019** [google-pay/flutter-plugin#193]
Cannot redirect to a gpay application (Andoroid, ios), through this plugin. Need an option to trigger the UPI application for payments in India.

**Comment by JlUgia** [comment]
Hi @abinvs-2019, this plugin uses the Google Pay and Apple Pay APIs to facilitate on Android and iOS respectively.
These APIs are not involved in the flow of funds, and diverge from UPI at their core.
With that said, there are [multiple packages to issue UPI transactions in pub.dev](https://pub.dev/packages?q=upi).
