### ISSUE TITLE
Depends on old SVG library.

### ISSUE THREAD

**Issue by darajava** [google-pay/flutter-plugin#195]
Because pay >=1.1.0 depends on pay_android ^1.0.9 which depends on flutter_svg ^1.0.0, pay >=1.1.0 requires flutter_svg ^1.0.0.
So, because AudioDiary depends on both flutter_svg ^2.0.2 and pay ^1.1.0, version solving failed.

I needed to downgrade, but then I lost features in my app. Can this be bumped?

**Comment by asaarnak** [comment]
Duplicate issue: https://github.com/google-pay/flutter-plugin/issues/184
