### ISSUE TITLE
apple pay "paymentData" not found

### ISSUE THREAD

**Issue by abdalmonem** [google-pay/flutter-plugin#199]
hi
after make an apple pay payment i get the token , but there is no "paymentData" parameter inside

**Comment by abdalmonem** [comment]
i got it wrong , sorry , i'll close this for now

**Comment by surveshoeb** [comment]
@abdalmonem did you get the details of paymentData?

**Comment by abdalmonem** [comment]
@surveshoeb yes.
i dont know if this info will be helpful:
 most payment getaways ask for token as base64", this plugin is gave you a row data and you should encode it by your self before pass it to the payment getaway
