### ISSUE TITLE
real device issue 

### ISSUE THREAD

**Issue by mdazadhossain95** [google-pay/flutter-plugin#205]
Gpay & Apple pay button is showing in the Android emulator & ios simulator. 
The problem is when I run that example in a real device time Gpay & Apple Pay button is not showing. 
![IMG_0909](https://github.com/google-pay/flutter-plugin/assets/58014179/6ca57dee-37e7-4526-a83d-58636a9c355e)

**Comment by pandeykushal** [comment]
did you find the solution i faced same problem and i am from Nepal so  i tryed by chandging my location also

**Comment by JlUgia** [comment]
Closing to continue the conversation in #207.

**Comment by mdazadhossain95** [comment]
@pandeykushal not yet
