### ISSUE TITLE
Real Device issue 

### ISSUE THREAD

**Issue by pandeykushal** [google-pay/flutter-plugin#207]
it is working fine i the  emulator but not showing in the real device  i am from nepal and tyed to change the location using VPN 
This picture is of emulator and 

![image](https://github.com/google-pay/flutter-plugin/assets/96460954/39dd6602-2caa-4ce5-8ec1-6ffee02d223e)

![Screenshot_1689837106](https://github.com/google-pay/flutter-plugin/assets/96460954/fa076cac-8dc1-4a91-a00e-9f254e2aa3d4)

**Comment by JlUgia** [comment]
Hi @pandeykushal.
The Google Pay button is shown when [the call to `isReadyToPay` method](https://developers.google.com/android/reference/com/google/android/gms/wallet/PaymentsClient#isReadyToPay(com.google.android.gms.wallet.IsReadyToPayRequest)) returns `true`. In short, your device needs to be signed in with a valid Gmail account and a minimum version Google Play services needs to be installed.  Check out the link to see the specific requirements, and ensure that your device meets that criteria. 

What's the target location in your VPN configuration?

**Comment by JlUgia** [comment]
Closing this issue for now.
Feel free to re-open if the underlying problem is not resolved.
