### ISSUE TITLE
How to customize the payment button, applying the google pay parameters (Android)

### ISSUE THREAD

**Issue by Ignaciomanchu1998** [google-pay/flutter-plugin#211]
I want to customize the button by applying the google pay parameters. However, I see that at the first view of the widget, it does not allow me. Any recommendation?

**Comment by JlUgia** [comment]
Hi @Ignaciomanchu1998.
What parameters are you intending to configure?

**Comment by JlUgia** [comment]
The background color can be configured using the `style` property for Apple Pay. Take a look at [the example](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/lib/main.dart#L147).
Google Pay will soon support a similar property to change the theme of the button.
The corner radius is also in the roadmap in this repo – you can keep track of it through #127.

**Comment by Ignaciomanchu1998** [comment]
Thanks, dear.

**Comment by BaudouinCS** [comment]
> Google Pay will soon support a similar property to change the theme of the button. The corner radius is also in the roadmap in this repo – you can keep track of it through #127.

Hi, is there any way to change it manually? My submission got rejected because my Google Pay button has a dark background for the dark theme (same issue for light theme) but I can't change the background color / theme of the button...
