### ISSUE TITLE
this merchant is having trouble accepting your payment at the moment. try using a different payment method [or_bibed_11] 

### ISSUE THREAD

**Issue by jrajora** [google-pay/flutter-plugin#212]
hi i found this one error while i use flutter_stripe for make payment integration in flutter application in android using Google Pay and while i try with test account it's working fine but while i switched from test mode to live i found below one error could you please help me out to resolve this error to finish 

this merchant is having trouble accepting your payment at the moment. try using a different payment method [or_bibed_11]

**Comment by JlUgia** [comment]
Good day @jrajora, have you submitted your application for approval using the [business console](http://g.co/pay/console)? If so, what's the status shown in the console?

**Comment by jrajora** [comment]
Good day @JlUgia Thanks for your prompt response 

Actually we are using Stripe Pay in which having functionality to use google pay and we are facing above error so can you please let me know is it required (mandatory) to submit application to business console while using GooglePay through Stripe Payment

**Comment by jrajora** [comment]
@JlUgia i'm really appreciate with your help and support  

i had feel the details on google pay console and after that on Test mode and Live Mode not working while i click on Google Pay button in not responding. can you please help me out for where i'm getting stuck

**Comment by JlUgia** [comment]
Has your integration been approved for production use in the business console – g.co/pay/console?
If so, make sure that you are initialising the Stripe library passing in your `stripePublishableKey`.

**Comment by Jbr99921** [comment]
@JlUgia i'm really appreciate with your help and support.

After complete my business console and submit screenshot which is required to share on console after approval i check in release mode of application and everything is working fine.
Thank you so much for your availability and response 👍

**Comment by dream78671** [comment]
ah where  ? 
how you submit ? 
it doesnt even give me an option 
ehh ? 

`Integrate with your Android app
There are no Android apps currently associated with <email address > as the account owner, admin, or user. To take action, you must be in one of those roles.`

**Comment by JlUgia** [comment]
Hi @dream78671, this list shows applications published in the Google Play store under the same account.
Make sure that your Android application is public in the store before requesting production access in the console.
Hope this helps.

**Comment by dotsconnections-dev** [comment]
@Jbr99921 Can you please guide me with your application screenshots for production approval !! I'm stuck with my application approval Google emailed me about the Google pay android mark which I already added in the application.
