### ISSUE TITLE
This merchant is having trouble accepting your payment right now by using different payment method OR_BIBED_11

### ISSUE THREAD

**Issue by Mayank22091995** [google-pay/flutter-plugin#217]
Describe the bug
I use the google pay integration of stripe in flutter but in android press the google pay button that time open the bottomsheet but after that some error show in production and working fine in development this error like this this merchant is having trouble accepting your payment right now by using different payment method OR_BIBED_11 and I also change the add live key and testenv false but still same error in production.

**Comment by DarkSealer** [comment]
I'm having the same problem. Any solution?

**Comment by JlUgia** [comment]
Before facilitating payments on production you need to submit your integration for approval in the [Pay & Wallet Business Console](g.co/pay/console). Once your integration is approved, you'll be operate in production.

**Comment by dream78671** [comment]
> Hi @JlUgia can you tell more about how to submit your integration for approval in the [Pay & Wallet Business Console](https://github.com/google-pay/flutter-plugin/issues/g.co/pay/console). Cause i have already configured profile in Business console and still have no idea where can i submit integration for approval in Pay Console .
> 
> Thank you.

yes - this same thing with me ...
Can you please provide us with any sort documentation/information's on how we go about i getting the integration approved by the Google Pay API team ? 
@JlUgia any advice/input on this issue ?

**Comment by dream78671** [comment]
@JlUgia 

- [ ] look at issue  https://github.com/google-pay/flutter-plugin/issues/217

**Comment by pandeykushal** [comment]
did you solve the issue 
![Screenshot_1702379812](https://github.com/google-pay/flutter-plugin/assets/96460954/abaad929-8c8b-4d89-b195-727863c28c03)

 i am getting same problem  as yours

**Comment by JlUgia** [comment]
The console is meant to be self-guiding. The process goes as follows:
0. Publish your application in the Google Play store
1. [Access the console](g.co/pay/console)
2. Create a business profile
3. Go to the "Google Pay API" section
4. Your published Android apps show under "Integrate with your Android app".
5. Select one of them to start the production approval process.

Let me know if this helps.

**Comment by JlUgia** [comment]
Feel free to reopen if the issue persist.
