### ISSUE TITLE
RawApplePayButton's semantics are broken 

### ISSUE THREAD

**Issue by romgrm** [google-pay/flutter-plugin#220]
Hello :) 

I'm opening a new issue related to this one : https://github.com/google-pay/flutter-plugin/issues/208 

The RawApplePayButton's semantics seem to be broken. When VoiceOver is activated, and you swipe from element to another, a debug message appears when the focus is on the button : 

`[Accessibility] Went all the way up the container chain from @, but could not find any container that was one of the ordered children of @.  This may be acceptable if it happened right around a layout change, but it would be best to double check by swiping left/right to see if you can get to all elements.`

Then it's impossible to swipe either left or right, as if the focus were stuck on the button. 

This error occurs when several elements follow each other, as in a ListView, Column, etc...

It seems that the VoiceOver is not able to distinguish the placement of the RawApplePayButton and so this stuck the focus afterward. 

This issue prevents some disabled users to pay with ApplePay. 

Flutter : 3.13.3 
iOS : 16.6.1 

Thanks 

https://github.com/google-pay/flutter-plugin/assets/72022928/5c927cf6-6cd6-4a71-9d5c-fef7da11bde3

**Comment by JlUgia** [comment]
Thank you for raising this @romgrm.
If you take a look at how the button is drawn, it's [standard platform drawing logic](https://github.com/google-pay/flutter-plugin/blob/main/pay_ios/ios/Classes/ApplePayButtonView.swift#L141). This may be related with how Flutter managers platform views on iOS.
Let me investigate a little further.

Feel free to add any additional evidence that may help resolve the issue.

**Comment by romgrm** [comment]
Bonjour @JlUgia :)

Yes, you're right, I quickly recreated the ios_pay package with a FlutterPlatformView and the problem is still there.

So I opened an issue on the Flutter repo about the UiKitView semantics problem. (https://github.com/flutter/flutter/issues/135504) 

A member reproduced it so I think we'll investigate in that way.

we'll keep in touch

**Comment by JlUgia** [comment]
I see this issues has been fixed on the Flutter repo.
Thank you for reporting @romgrm .
