### ISSUE TITLE
Typo error in minimumButonWidth

### ISSUE THREAD

**Issue by Serajj** [google-pay/flutter-plugin#221]
.pub-cache/hosted/pub.dev/pay-1.1.0/lib/src/widgets/apple_pay_button.dart:42:43: Error: Member not found: 'minimumButonWidth'.
  })  : assert(width >= RawApplePayButton.minimumButonWidth),
  
  
  There is a typo error  in RawApplePayButton.minimumButonWidth.  , please change minimumButonWidth to minimumButtonWidth.

**Comment by abinvs-2019** [comment]
Can you provide more info?

**Comment by abinvs-2019** [comment]
Its probably you are calling wrong enum.
