### ISSUE TITLE
Inconsistent Data Format Returned from onPaymentResult Function

### ISSUE THREAD

**Issue by ibrahimmohamed2411** [google-pay/flutter-plugin#222]
Issue Description:
The current behavior of the onPaymentResult function in the package is causing inconsistency in the format of payment result data between Android and iOS.

Issue Details:
Version: 1.1.2

Current Behavior:
Android (Non-JSON Format):
{apiVersion: 2, apiVersionMinor: 0, paymentMethodData: {description: US Credit: Visa •••• 4242, info: {billingAddress: {address1: 1600 Amphitheatre Parkway, address2: , address3: , administrativeArea: CA, countryCode: US, locality: Mountain View, name: Card Holder Name, phoneNumber: 6505555555, postalCode: 94043, sortingCode: }, cardDetails: 4242, cardNetwork: VISA}, tokenizationData: {token: {
        "id": "------------",
        "object": "token",
        "card": {
          "id": "------------",
          "object": "card",
          "address_city": "Mountain View",
          "address_country": "US",
          "address_line1": "1600 Amphitheatre Parkway",
          "address_line1_check": "unchecked",
          "address_line2": null,
          "address_state": "CA",
          "address_zip": "94043",
          "address_zip_check": "unchecked",
          "brand": "Visa",
          "country": "US",
          "cvc_check": null,
           "dynamic_last4": "4242",
          "exp_month": 12,
          "exp_year": 2025,
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": null,
          "tokenization_method": "android_pay",
          "wallet": null
        },
        "client_ip": "209.85.198.208",
        "created": 1696241400,
        "livemode": false,
        "type": "card",
        "used": false
      }, type: PAYMENT_GATEWAY}, type: CARD}}
      
IOS (Non-JSON Format):
  {paymentMethod: {displayName: Simulated Instrument, type: 0, network: AmEx}, transactionIdentifier: Simulated Identifier, token: , billingContact: {name: {nameSuffix: , nickname: , namePrefix: , middleName: , givenName: ibrahim, phoneticRepresentation: {namePrefix: null, givenName: , nickname: null, phoneticRepresentation: null, middleName: , familyName: , nameSuffix: null}, familyName: Mohamed}, postalAddress: {subLocality: , street: Sxsxs , subAdministrativeArea: , isoCountryCode: US, city: Asdddd, state: AL, postalCode: 12345, country: United States}}}
  which are not a json format

**Comment by JlUgia** [comment]
Hi @ibrahimmohamed2411, these responses are generated on the native ends on Android and iOS respectively, and hence not intended to adhere to any typing contract. These objects are relayed to the Flutter layer as they are returned from the Google Pay and Apple Pay libraries respectively.

Would you see a benefit in wrapping the responses in superobjects containing common properties and the raw data too?
Can you share your concrete use cases where this may be valuable?

**Comment by JlUgia** [comment]
Closing this issue, feel free to reopen if you can provide additional input.
