### ISSUE TITLE
No such token error from stripe - Pay Plugin on iOS device

### ISSUE THREAD

**Issue by Daniel-Sogbey** [google-pay/flutter-plugin#223]
I get this response back from stripe on my iOS device

`＜くへくくくくくく＞＞＞＞＞＞＞stripenvalidRequestError： No such token： Dz6fgxM//DrthhM+Y8j/KXIqA
gr TBNAEbNRDqfYJsit1eG9qxEmMTDArpmyEJ7V8sbKmGgm7 jheoBIGKNtoaJGqjYcE6zwn41G0+39WInGHoHzSme
BTk29/t6jov1/5eBg/qG1PnbdFhm/Vk7vyAyzfzxjm6UJEJF1sZmwnNeNCWzp02PjlyPPLM82qqxgww17wGZ6C
nfJUy1GVbGUN2GmN+4bgKvc2mLFTewg1VOeKH3b7/3XNds8RqnwDlyLzpZkG+yf/WERi1HWBIpNgJAH3P8v+t/dK
TQbjCnDBcrOUwB227L9ID8NZpOBZtm4qTiFZXmsIRcUdWUl8EcvSQj6PXwtLtcq945MEdSxLRuR6VPvOBBlsHhgdR
9YJJ//q1wiDezBnsceF90=='
at StripeError generate (D: \focusppc\clickso_apis_backend\node_modules \stripe\lib\Err
or. js: 38:16)
at res. toJSON. then.StripeAPIError .message (D: \focusppc\clickso_apis_backend\node_modu
les \stripe\lib\StripeResource. js: 190:35)
at process. process 1cksAndRejections (node: internal/process/task queues:95:5)
StripeInvalidRequestError", resource missing',
https://stripe.com/docs/error-codes/resource-missing',
message: "No such token: Dz6fgxM//DrtwhM+Y8j/KXIqAgrBNAEbNRDqfYJsitleG9qxEmMtTDArpm
yEJ7V8sbKmGgm7 jheoBIGKNtoaJGqjYcE6zwn41G0+39WJnGHoHzSmeBTk29/t6joVl/5eBg/qG1PnbdFMhm/Vk7v
yAyZfzxjmuJEJFIsZmnNeNCWzpQ2PjLyPPLMM82qqxgww17wGz6Cnf JUy1GVbGUN2Gmw+4bgKvc2mLFTeg1VO
eKH3b7/3XNds8RqnwDlyLzpZkG+yf/WERi1HWVB1pNgJAH3P8v+t/dKTObjCnDBcrOUwB227L9ID8NZpOBZtm4qTi
`FZXmsIRcUdWU|8EcvSQj6PXWLtcq945MEdSxLRuR6VPvOBBIsHhgdR9Y]J//q1wiDezBnsceF9Q=``

How can I solve it

**Comment by JlUgia** [comment]
Hi @Daniel-Sogbey, this repository hosts a Flutter plug-in supporting Google Pay and Apple Pay, so you likely won't get the most accurate guidance on PSP-specific queries. 

Taking a quick look, it appears that your Stripe account in the backend does not expect/recognize the token you are sending. Make sure the account and [environment](https://stackoverflow.com/questions/33137053/no-such-token-error-upon-submitting-payment-request-to-stripe) you are using to create the token on the server match your application configuration.

Also, take a look at [Stripe's docs](https://stripe.com/docs/libraries/android), and [GH repo for Android](https://github.com/stripe/stripe-android) and [Flutter](https://github.com/flutter-stripe/flutter_stripe).

/cc @remonh87 @jonasbark
