### ISSUE TITLE
i want test auth token but give examplePaymentMethodToken this version ,,,, in bangladesh

### ISSUE THREAD

**Issue by mostafiz9900** [google-pay/flutter-plugin#225]
{apiVersion: 2, apiVersionMinor: 0, paymentMethodData: {description: Test Card: Amex •••• 0005, info: {billingAddress: {address1: 1600 Amphitheatre Parkway, address2: , address3: , administrativeArea: CA, countryCode: US, locality: Mountain View, name: Card Holder Name, phoneNumber: 6505555555, postalCode: 94043, sortingCode: }, cardDetails: 0005, cardNetwork: AMEX}, tokenizationData: {token: examplePaymentMethodToken, type: PAYMENT_GATEWAY}, type: CARD}}

**Comment by JlUgia** [comment]
Hi @mostafiz9900, this is the [expected response](https://developers.google.com/pay/api/android/reference/response-objects#example) when using the API in `TEST` mode.
You can use the [Pay & Wallet console](https://pay.google.com/business/console) to enable production access. Your application needs to be public in the Play Store, and you need to integrate with a [supported payment gateway](https://g.co/pay/processors).

You can use our documentation site at g.co/pay/api to quickly find this and other relevant information.

Feel free to re-open the thread if you have additional questions.
