### ISSUE TITLE
I am getting this error like Null.

### ISSUE THREAD

**Issue by akshay-git20** [google-pay/flutter-plugin#228]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      Pay.userCanPay (package:pay/src/pay.dart:58:50)
<asynchronous suspension>
#1      _PayButtonState.userCanPay (package:pay/src/widgets/pay_button.dart:121:14)
<asynchronous suspension>

**Comment by yaksh1** [comment]
@akshay-git20 can you show how to reproduce the error, I would like to solve the issue.

**Comment by JlUgia** [comment]
Hi @akshay-git20.
Note that this plugin [supports iOS and Android](https://github.com/google-pay/flutter-plugin/blob/main/pay/lib/src/pay.dart#L7) at the moment. What platform are you using the plugin with?

**Comment by JlUgia** [comment]
Feel free to reopen this issue if you can add additional information.
