### ISSUE TITLE
UserCanPay function returning false

### ISSUE THREAD

**Issue by moses-sichone** [google-pay/flutter-plugin#246]
_payClient.userCanPay(PayProvider.google_pay) returns false even though the device has Google Pay configured and the payment window shows when 
//
final result = await _payClient.showPaymentSelector(
      PayProvider.google_pay,
      items,) 
//
is run. 
I am using 
mad_pay: ^1.1.2
Android version: 14
device: Samsung S21 5G

Can you please advise why this may be happening?

Also i tried configuration details from Asset(json) and String

**Comment by JlUgia** [comment]
Hey @moses-sichone, it looks like you are using a different package.
