### ISSUE TITLE
Pay plugin showing success for failed apple pay transaction in flutter app on apple pay sheet

### ISSUE THREAD

**Issue by khanawansocialb** [google-pay/flutter-plugin#248]
I have successfully implemented apple pay using the pay plugin in my e-commerce flutter app and it works just fine. The only problem is that the apple pay sheet, upon the completion of transaction, shows done (success) for both failed and successful transactions. I am showing an alert dialog when failure occurs, but still this issue is misleading and unfriendly to the users. I have tested this with Sandbox and real apple wallets and the result is same. There's no issue in my backend either as I have tested a transaction without invoking my backend endpiont and the result is no different. I am using final res = await _payClient.showPaymentSelector(PayProvider.apple_pay, _paymentItems); to get the token and send this to backend. It seems that my Apple Pay configuration files are also without issues; if there had been any problems, transactions wouldn't have been completed in the first place. My pay plugin version is 1.1.2 and my dart sdk is >=3.0.3 <4.0.0. I have provided the screenshot for a failed transaction below:

![76cc346f-f8e9-40c3-8613-0d420ec66e0d](https://github.com/google-pay/flutter-plugin/assets/147700497/eaa7baaf-d217-41bb-bb49-e8fd1f989f41)

**Comment by JlUgia** [comment]
Good day @khanawansocialb, [this PR](https://github.com/google-pay/flutter-plugin/pull/200) adds functionality to do just that. Make sure to subscribe to receive a notification when it's merged.

**Comment by khanawansocialb** [comment]
You guys just released Pay: 2.0.0 and this issue is still there. Very sloppy
