### ISSUE TITLE
Apple pay bottom sheet displays "done" even when a transaction fails

### ISSUE THREAD

**Issue by sarthakrungta** [google-pay/flutter-plugin#250]
I am using the [pay plugin](https://pub.dev/packages/pay) in Flutter to enable Apple pay into my app The funactioanlity runs smoothly but I am facing a UI related issue in Apple Pay payments.

If the user's card is declined, the apple pay bottom sheet still displays a tick and sayd "Done". The response body sent by Apple to my payment provider does say that the card was declined but in the UI, the user sees "Done"

![image](https://github.com/google-pay/flutter-plugin/assets/42744472/8ccf3c6d-1815-4f7f-9947-0396883a6641)

Ideally, the UI of the bottom sheet should also say "Payment failed" or "Payment not completed" like in web or native integrations of Apple Pay: 

![image](https://github.com/google-pay/flutter-plugin/assets/42744472/bc8c5e83-160f-47c7-aab2-d51e934e6670)

![image](https://github.com/google-pay/flutter-plugin/assets/42744472/fc5afde5-5bae-4b74-9504-3f8277a65903)

**Comment by khanawansocialb** [comment]
I am facing the same issue and opened a similar issue a few days ago. They recently released the 2.0.0 version and I thought they must've fixed it, but they haven't

**Comment by JlUgia** [comment]
Hi @sarthakrungta, there's an open pull request that adds that feature (see #200).
You can use the PR to keep track of the feature.
@khanawansocialb you are most welcome to keep track of progress there too.
