### ISSUE TITLE
Google Pay :  Incomplete Payment Response Persisting After Google Pay Transition from TEST to PRODUCTION Mode

### ISSUE THREAD

**Issue by dihsarjr** [google-pay/flutter-plugin#253]
Even after transitioning from TEST to PRODUCTION mode on Google Pay, I'm still receiving an incomplete payment response, returning "{paymentData: null, paymentMethod: null, transactionIdentifier: null}".

**Comment by JlUgia** [comment]
Hello @dihsarjr, I don't recognize these fields in the Google Pay response, where are you getting this from?
What response where you receiving in `TEST` mode?

**Comment by dihsarjr** [comment]
The issue automatically resolved three days after Google Pay's production approval, Thank you.
