### ISSUE TITLE
How to only support google pay or apple pay

### ISSUE THREAD

**Issue by szhupeng** [google-pay/flutter-plugin#254]
How to configure to only support google pay or apple pay

**Comment by JlUgia** [comment]
Hi @szhupeng, the configurations for Apple and Google Pay are platform specific and independent from each other.
Google Pay is only supported on Android, and Apple Pay on iOS (see the [compatibility section in the readme](https://github.com/google-pay/flutter-plugin/tree/main/pay#platform-support) for more details).
In addition, you need to explicitly add the `GooglePayButton` or `ApplePayButton` in your layout to enable each payment facilitator. See the [example in the readme](https://github.com/google-pay/flutter-plugin/tree/main/pay) for more info.
