### ISSUE TITLE
Payment 

### ISSUE THREAD

**Issue by pawan14325** [google-pay/flutter-plugin#257]
How to check payment history and where is this listed

**Comment by cookii-king** [comment]
I think you have to ingrate with third party payment processors such as Stripe or Braintree. I found Braintree was easier to implement and I don't know why 😭 I just started implementing pay package yesterday.

**Comment by JlUgia** [comment]
Hello @pawan14325, as @cookii-king points out, Google Pay does not process payments. It facilitates the payment process by offering encrypted payment credentials from your users' Google accounts to your payment processor.
Here's the [list of supported processors](g.co/pay/processors) with Google Pay.
