### ISSUE TITLE
On Android phones,  running the main.dart file in the pay/example  prompts an error

### ISSUE THREAD

**Issue by LingLuoJack** [google-pay/flutter-plugin#264]
flutter-plugin-main/pay/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: 错误: 找不到符号
      flutterEngine.getPlugins().add(new io.flutter.plugins.pay_android.PayPlugin());
                                                                       ^
  符号:   类 PayPlugin
  位置: 程序包 io.flutter.plugins.pay_android
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Please help me successfully run the project.

**Comment by JlUgia** [comment]
Hi @LingLuoJack, can you add more details about the compilation error you see in the output?

**Comment by LingLuoJack** [comment]
thank you , I  have resolved this error.
