### ISSUE TITLE
Incomplete Payment Result

### ISSUE THREAD

**Issue by barokahttaufik** [google-pay/flutter-plugin#266]
i have log this function in native android

private fun handlePaymentSuccess(paymentData: PaymentData?) {
        if (paymentData != null) {
            println("ORIGINAL PAYMENT DATA : ${paymentData.toJson()}")
            loadPaymentDataResult.success(paymentData.toJson())
        } else {
            loadPaymentDataResult.error(
                    CommonStatusCodes.INTERNAL_ERROR.toString(),
                    "Unexpected empty result data.",
                    null)
        }
    }
    
    
and this is the result 

ORIGINAL PAYMENT DATA : {"apiVersion":2,"apiVersionMinor":0,"paymentMethodData":{"description":"Test Card: Visa •••• 1111","info":{"assuranceDetails":{"accountVerified":true,"cardHolderAuthenticated":true},"billingAddress":{"address1":"1600 Amphitheatre Parkway","address2":"","address3":"","administrativeArea":"CA","countryCode":"US","locality":"Mountain View","name":"Card Holder Name","phoneNumber":"6505555555","postalCode":"94043","sortingCode":""},"cardDetails":"1111","cardNetwork":"VISA"},"tokenizationData":{"token":"{\"signature\":\"MEQCIFl6g3EWsQAc7S5u8SubeMDqyKu55u5v45hfm\/iOzCwPAiAU0k8rMHXlc7X0\/xq8geIHe2uYh\/OQ2Qk1RliPA\/QEnQ\\u003d\\u003d\",\"intermediateSigningKey\":{\"signedKey\":\"{\\\"keyValue\\\":\\\"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQ0eWpUAFdJQVoh8fnfh4StvhFABwJAVgnLRK8lFMj8wKdHoM+EDZYoNBVZOPRjP5mK9TMyZ2S375ON9n4EHvmw\\\\u003d\\\\u003d\\\",\\\"keyExpiration\\\":\\\"1718169175143\\\"}\",\"signatures\":[\"MEUCIHc8pt6rwn5ck3d\/o9sNnR70Ah1pW4EyljWkowuNfYvtAiEAv6golLm+8H3Yg4bnDrZtsNdcGZMzZGYpIkbZxlQZLuE\\u003d\"]},\"protocolVersion\":\"ECv2\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"VuY0X5izcEn3laiFywirTTNwR0wysc4B77kRLLRm9TkYGIVElQ3q7jK5pS61pGuWfSap+tv22oSqEOSxSJfsX3t50ZsmkVhgm1YG2tfFAjX6\/rNTB52U6bzMaOTXbXmXQydKgHZ1rSoKXeJP6NC\/FVq6P4+0SyDfaHAjnY1OYQ5iHYgkPYYO\/keypIHBqoZtF423iyf1j01ozRTBwgjFwsjKY\/MWZCMt2SaIoBRw2DymsHEJLnMPY62rjeJOs8LmjFTemyjrxyHe\/WpD8LNwK+rXodGC2mMqVDpElHFhNWnsyFST+O6o54HDXGpV3asggRQ678Ca9wPrB9PSdOQB6QRAYcDHfdyak9WH1vhfNuSBPOegIX1Vd+p6fIcvIsyIoiRkPtxgo1t3F6qCuI85GD9UiuwH1mMoy56vEFTuKvwvG6xc67aXMUirxzngWB9NWElSPHSdefGDbw7jV5WSmRafmB6cKoI5DRSw7vjrz5+WMnbUhDVWWGw0AdVbYf5USQjunYbQs2u1bQM0pTPmYx9+F46Mg1Yvs06y8HvJOn2eUWE1nQu9Sfw8kMqNqJcN\\\",\\\"ephemeralPublicKey\\\":\\\"BMs9P80SCK4LF0bJb9R20TwfXVK6vb6DHoPKVsbWbGIbzejSMNyV90jCM\/GFWoZZ2hPoHMq9Q0pjuE\/uqUnyMCw\\\\u003d\\\",\\\"tag\\\":\\\"6gPWP2wn6FIG8Hv6dZA1JpitXpKjwQ1WtsRXzdZ07TE\\\\u003d\\\"}\"}","type":"PAYMENT_GATEWAY"},"type":"CARD"}}

but the result in flutter is

final result = await payClient?.showPaymentSelector(payProvider, donationItems);
print('Result : ${result}');

Result : {apiVersion: 2, apiVersionMinor: 0, paymentMethodData: {description: Test Card: Visa •••• 1111, info: {assuranceDetails: {accountVerified: true, cardHolderAuthenticated: true}, billingAddress: {address1: 1600 Amphitheatre Parkway, address2: , address3: , administrativeArea: CA, countryCode: US, locality: Mountain View, name: Card Holder Name, phoneNumber: 6505555555, postalCode: 94043, sortingCode: }, cardDetails: 1111, cardNetwork: VISA}, tokenizationData: {token: {"signature":"MEQCIFl6g3EWsQAc7S5u8SubeMDqyKu55u5v45hfm/iOzCwPAiAU0k8rMHXlc7X0/xq8geIHe2uYh/OQ2Qk1RliPA/QEnQ\u003d\u003d","intermediateSigningKey":{"signedKey":"{\"keyValue\":\"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQ0eWpUAFdJQVoh8fnfh4StvhFABwJAVgnLRK8lFMj8wKdHoM+EDZYoNBVZOPRjP5mK9TMyZ2S375ON9n4EHvmw\\u003d\\u003d\",\"keyExpiration\":\"1718169175143\"}","signatures":["MEUCIHc8pt6rwn5ck3d/o9sNnR70Ah1pW4EyljWkowuNfYvtAiEAv6golLm+8H3Yg4bnDrZtsNdcGZMzZGYpIkbZxlQZLuE\u003d"]},"protocolVersion":"ECv2","signedMessage":"{\"encrypt

it looks like the results were cut off halfway through

**Comment by JlUgia** [comment]
Hi @barokahttaufik, the object is certainly there. You can access the information navigating the properties in the object to verify that.
To me, this looks like message truncation from your logging system (see [log truncation in Flutter](https://stackoverflow.com/questions/49138971/logging-large-strings-from-flutter)). 

Feel free to reopen the case if you can confirm that the issue is related to this library.
