### ISSUE TITLE
How to change the language of apple pay bottom sheets

### ISSUE THREAD

**Issue by mo7amedaliEbaid** [google-pay/flutter-plugin#268]
I am using this package in a flutter app that the user can change language , Supported languages are Arabic "ar" and English "en", Specially for apple pay , is it possible to change the language of the button and bottom sheets.

**Comment by JlUgia** [comment]
Hello @mo7amedaliEbaid, to my knowledge, the language of the button and the bottom sheet is defined by the system locale and not configurable using the Apple Pay API (see https://developer.apple.com/design/human-interface-guidelines/apple-pay#Button-types).
