### ISSUE TITLE
How Google Pay and Apple Pay works

### ISSUE THREAD

**Issue by kekko7072** [google-pay/flutter-plugin#27]
Hey I am new at Payment in flutter and I have some simple questions, I am searching for a payment method for a service app (like uber or food delivery). 

1) Can I use this package to implement this kind of payment (service/ product payment) ?  

2) Where I add my billing information for apple and google? 

> For example in Stripe I have an account with my own api where I add my billing information and check payment status and analytics
3) After I have configured the app and all the merchantID etc... When and how Apple an google will send my user payments?

4) Is there a tax like for in app purchase?

Thank you so much. 

**Seems simple things but I think should be added to package description to help distribute the usage of this package to new adopter like me :)**

**Comment by JlUgia** [comment]
Hi @kekko7072.
1. You **can** use regular payment mechanisms (non-store) for physical services.
2. Services like Apple Pay or Google Pay do not replace your payment service provider, but work together in combination. Take a look at the list of supported payment providers for [Apple Pay](https://developer.apple.com/apple-pay/payment-platforms/) and [Google Pay](g.co/pay/api).
3. Apple Pay and Google Pay facilitate the payment method selection for your users. Once they choose one, the payment method is encrypted and returned back to your application, which you can then use to create an order against your PSP (similar to how you do for orders with regular cards). Take a look at the payment result handling sections in the integration guides for [Apple Pay](https://developer.apple.com/apple-pay/payment-platforms/) (on the "Handle Payment Success or Failure" section) and [Google Pay](https://developers.google.com/pay/api/android/guides/tutorial#paymentdata).
4. Using both the Apple Pay and Google Pay APIs for mobile is free today.

Resources with these topics are included in the table at the end of the readme. Were you able to find them?

**Comment by kekko7072** [comment]
Thank you so much.
