### ISSUE TITLE
is  google pay  support flutter web . can i use this  on my  web  app

### ISSUE THREAD

**Issue by samithe7** [google-pay/flutter-plugin#28]

**Comment by JlUgia** [comment]
Hi @samithe7. 
Google Pay has [JS libraries](https://developers.google.com/pay/api/web/overview) for the Web, although they are not part of this plugin yet.
In this plugin, as of today, Android and iOS are supported. Said so, with the stable release of Web in 2.2, it's time to include it in the pipeline.
I've created a new issue (#30) to keep track of it.

**Comment by samithe7** [comment]
thanks  . waiting for web support

**Comment by KSingh1980** [comment]
Making JS libraries work on Flutter is another nightmare.  Payment should be a native solution in such a framework if google wants to spread google pay usage.
