### ISSUE TITLE
Cannot build android application getting this error => Expecting a parameter declaration

### ISSUE THREAD

**Issue by feemagdev** [google-pay/flutter-plugin#29]
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
lib\main.dart:1
e: C:\Users\faheem\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pay_android-1.0.1\android\src\main\kotlin\io\flutter\plugins\pay_android\GooglePayHandler.kt: (112, 27): Expecting a parameter declaration
e: C:\Users\faheem\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pay_android-1.0.1\android\src\main\kotlin\io\flutter\plugins\pay_android\PayMethodCallHandler.kt: (37, 28): Expecting a parameter declaration
e: C:\Users\faheem\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pay_android-1.0.1\android\src\main\kotlin\io\flutter\plugins\pay_android\PayMethodCallHandler.kt: (53, 52): Expecting a parameter declaration

e: C:\Users\faheem\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pay_android-1.0.1\android\src\main\kotlin\io\flutter\plugins\pay_android\PayPlugin.kt: (38, 79): Expecting a parameter declaration
e: C:\Users\faheem\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pay_android-1.0.1\android\src\main\kotlin\io\flutter\plugins\pay_android\PayPlugin.kt: (52, 67): Expecting a parameter declaration

FAILURE: Build failed with an exception.

**Comment by JlUgia** [comment]
Hey @feemagdev,
What `minSdkVersion` and `ext.kotlin_version` are you using?
The plugin usses `19` and `1.4.20` respectively.
If adjusting that does not solve the issue, can you share more about your Android configuration?

**Comment by feemagdev** [comment]
> Hey @feemagdev,
> What `minSdkVersion` and `ext.kotlin_version` are you using?
> The plugin usses `19` and `1.4.20` respectively.
> If adjusting that does not solve the issue, can you share more about your Android configuration?

Thanks solved the problem. i am not using correct kotlin version.

**Comment by akillika** [comment]
I too get same problem
