### ISSUE TITLE
Check if card is just registered  

### ISSUE THREAD

**Issue by kekko7072** [google-pay/flutter-plugin#35]
How cam I check if Apple Pay or Google Pay has just a card registered and ready to use ? And there is a way to send user to add card to those payment app?

**Comment by JlUgia** [comment]
Hi kekko7072, both Google Pay and Apple Pay offer this functionality in different ways, and both are exposed through the plugin.
* Google Pay: You can check whether a user has an existing payment method saved that adheres to the supported forms of payment in your application, with the `existingPaymentMethodRequired` property in the `IsReadyToPayRequest`. Take a look at the [docs](https://developers.google.com/pay/api/android/reference/client#isReadyToPay) for more info. To enable this behavior in your Flutter application, set the `existingPaymentMethodRequired` prop to true in [your Google Pay configuration JSON file](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_google_pay.json).
* Apple Pay: This is the default behavior on Apple Pay if you specify a list of `supportedNetworks` in [your configuration](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json). Take a look at the [Apple Pay reference](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationcontroller/1649457-canmakepayments) to learn more.

**Comment by sebastianbuechler** [comment]
> Hi kekko7072, both Google Pay and Apple Pay offer this functionality in different ways, and both are exposed through the plugin.
> 
> * Google Pay: You can check whether a user has an existing payment method saved that adheres to the supported forms of payment in your application, with the `existingPaymentMethodRequired` property in the `IsReadyToPayRequest`. Take a look at the [docs](https://developers.google.com/pay/api/android/reference/client#isReadyToPay) for more info. To enable this behavior in your Flutter application, set the `existingPaymentMethodRequired` prop to true in [your Google Pay configuration JSON file](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_google_pay.json).
> * Apple Pay: This is the default behavior on Apple Pay if you specify a list of `supportedNetworks` in [your configuration](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json). Take a look at the [Apple Pay reference](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationcontroller/1649457-canmakepayments) to learn more.

@JlUgia Thanks for the resources. Is there a direct way for a flutter app to check if a specific credit card of the user is already registered within Google Pay / Apple Pay and if not, redirect to the Google Pay / Apple Pay App for starting the registration process? 

For example, Neobank Revolut allows to have multiple cards and displays a button at the bottom of their card detail view which says "Add to G Pay", but only if it's not yet registered with Google Pay.
