### ISSUE TITLE
Error running flutter pub get in flutter-plugin/pay

### ISSUE THREAD

**Issue by Ritsz123** [google-pay/flutter-plugin#38]
I tried to run flutter pub get in flutter-plugin/pay/ but i'm getting this error
`Because every version of flutter_test from sdk depends on test_api 0.3.0 and mockito >=4.1.2 <=5.0.0-nullsafety.7 depends on test_
api ^0.2.19-nullsafety, flutter_test from sdk is incompatible with mockito >=4.1.2 <=5.0.0-nullsafety.7.
So, because pay depends on both flutter_test any from sdk and mockito ^4.1.3, version solving failed.
`
_Edit:_  found solution for this issue it is because the version used in pay/pubspec.yaml is `mockito: ^4.1.3` which should be updated to `mockito: ^5.0.0`

**Comment by anasnaji25** [comment]
try this 
 `flutter pub add pay`

but better to upgrade other plugins also 

use this cmd to upgrade all your dependency's
`flutter pub upgrade --major-versions`

while upgrading the dependency's you may get some error

**Comment by JlUgia** [comment]
Hi @Ritsz123, thanks for reporting the issue.
We've bumped dependency versions in 1.0.2.
That should solve the issue for you.

**Comment by JlUgia** [comment]
Did this make it work for you @Ritsz123?

**Comment by Ritsz123** [comment]
@JlUgia Yeh it works..
