### ISSUE TITLE
Include the expectation on `minSdkVersion` in the docs

### ISSUE THREAD

**Issue by JlUgia** [google-pay/flutter-plugin#39]
When Android applications using the plugin need to include their own native ends, there's a requirement for them to use at least the same `minSdkVersion` and `ext.kotlin.version` as the Android side in the plugin.

Confirm this scenario and add explicit guidance in the documentation.
Related to https://github.com/google-pay/flutter-plugin/issues/29.

@domesticmouse, I've seen this issue in other packages as well, are you able to confirm whether this is known and accurate?

**Comment by domesticmouse** [comment]
Android isn't something I know a lot about, but it sounds reasonable. 

@RedBrogdon any ideas who to follow this up with?

**Comment by RedBrogdon** [comment]
I'm surprised the compiler isn't able to give a more useful error message than the one quoted in that issue.

To more directly answer your question, I would definitely make a point of the minimum SDK versions if they're higher than Flutter's defaults for Android. @blasten, is there anything else you'd recommend?

**Comment by blasten** [comment]
> When Android applications using the plugin need to include their own native ends

does it refer to other Android plugins? What does native ends refer to?

> Include the expectation on minSdkVersion in the docs

We recently added a [message](https://github.com/flutter/flutter/blob/811f0d9a159ca3bf2a5831c17fe407862af3dc90/packages/flutter_tools/lib/src/android/gradle_errors.dart#L389-L394) to the Flutter tool that guides users when a plugin requires a higher `minSdkVersion` than the one defined in the Flutter template (API level 16).
