### ISSUE TITLE
[ApplePay] Ability to Hide Shipping and Contact when not needed

### ISSUE THREAD

**Issue by hkhars** [google-pay/flutter-plugin#40]
In our case, we don't need users CONTACT and SHIPPING information.
We would like to have the ability to make them hidden/not required during payment.

I've tried to remove `requiredShippingContactFields` & `requiredBillingContactFields` fields from `default_payment_profile_apple_pay.json` but they are still required

**Comment by JlUgia** [comment]
Hi @hkhars. Thanks for reporting.
It seems that the iOS native end is not adequately configured to listen to shipping and billing requirements.
A fix is coming out tomorrow. I'll refer this issue in the PR to keep it up to date.

**Comment by JlUgia** [comment]
Version 1.0.3 is out @hkhars.
Take a look and feel free to re-open if the issue persists.

**Comment by hkhars** [comment]
@JlUgia I've done a quick test and the issue is resolved.
Thank you very much for the quick support.
