### ISSUE TITLE
Getting null in `token` in response of `showPaymentSelector`

### ISSUE THREAD

**Issue by awazgyawali** [google-pay/flutter-plugin#44]
As title explains this is what I am getting after a successful payment from apple pay. I believe token should be in response of the apple pay.
<img width="301" alt="Screen Shot 2021-05-27 at 23 02 36" src="https://user-images.githubusercontent.com/10810343/119869154-a2329180-bf3f-11eb-965d-7ebd374b80fd.png">

**Comment by JlUgia** [comment]
Hi @awazgyawali, are you using a simulator? The token comes back empty when paying through a simulator. Here are some related resources:
* [payment.token empty on an iOS simulator (Apple Dev forums)](https://developer.apple.com/forums/thread/44972)
* [Sandbox testing with real devices for Apple Pay (Apple Developer docs)](https://developer.apple.com/apple-pay/sandbox-testing/)
* [`didAuthorizePayment` not returning any value (StackOverflow)](https://stackoverflow.com/questions/48423739/pkpaymentauthorizationviewcontroller-didauthorizepayment-not-returning-token-val)

Going forward, do rely on the documentation for each provider to learn more about provider-specific behavior (Apple Pay in this case).

**Comment by awazgyawali** [comment]
@JlUgia You indeed are right, the misconception I had was because of the older SDK that I used to use `flutter_stripe`. It used to give token on simulators and after I migrated the package to `pay` it didn't give token. 

Probably maintainer hard coded test token as a response on simulator.
