### ISSUE TITLE
userCanPay(PayProvider.apple_pay) return always false to me

### ISSUE THREAD

**Issue by DineshTaral12** [google-pay/flutter-plugin#46]
The app is working fine in simulator with simulated card but when i running same code in physical devices, then userCanPay(PayProvider.apple_pay) always retruning false.

**Comment by awazgyawali** [comment]
@DineshTaral12 Do you have apple pay configured/enabled on your real device?

**Comment by JlUgia** [comment]
Hi @DineshTaral12, take a look at the [`canMakePayments` call on the Apple Pay docs](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationviewcontroller/1616192-canmakepayments). In short,  your device needs to be able to make payments, and have cards that match the payment methods supported if you set the `supportedNetworks` property in your configuration.
