### ISSUE TITLE
Unable to build Pay

### ISSUE THREAD

**Issue by TomMichalkevic** [google-pay/flutter-plugin#47]
Hi,

I am getting this weird issue when building:
`e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.2/android/src/main/kotlin/io/flutter/plugins/pay_android/GooglePayHandler.kt: (112, 27): Expecting a parameter declaration
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.2/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (37, 28): Expecting a parameter declaration
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.2/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (53, 52): Expecting a parameter declaration
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.2/android/src/main/kotlin/io/flutter/plugins/pay_android/PayPlugin.kt: (38, 79): Expecting a parameter declaration
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.2/android/src/main/kotlin/io/flutter/plugins/pay_android/PayPlugin.kt: (52, 67): Expecting a parameter declaration`

Any advice on how to fix it?

**Comment by JlUgia** [comment]
Hi @TomMichalkevic, this could be a duplicate of https://github.com/google-pay/flutter-plugin/issues/29. Google Pay requires a `mindSdkVersion` of `19`. We have an issue to add that to the main readme.
Take a look and see if that solves it for you too.

**Comment by TomMichalkevic** [comment]
@JlUgia thanks for the quick reply. I have `minSdkVersion` as 21 so that is in order. However, after upgrading Koltin and gradle to latest versions, the problem seems to be gone. Thanks for looking into it. Will close the issue now.
