### ISSUE TITLE
GooglePayButton is not showing.

### ISSUE THREAD

**Issue by Nisarg12** [google-pay/flutter-plugin#49]
I've place a GooglePayButton but it does not show. Enabling debug paint, you can see that it is very tiny. Setting height and width parameters also do not help.
![image](https://user-images.githubusercontent.com/28131554/120468119-80f9f700-c3be-11eb-97d2-24f84e45e1e5.png)

I get these errors:
`E/flutter (14723): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: 'package:pay_platform_interface/core/payment_configuration.dart': Failed assertion: line 55 pos 16: 'configuration.containsKey('provider')': is not true., stack trace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (14723): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (14723): #2      new PaymentConfiguration._ (package:pay_platform_interface/core/payment_configuration.dart:55:16)
E/flutter (14723): #3      PaymentConfiguration.fromAsset (package:pay_platform_interface/core/payment_configuration.dart:85:33)
E/flutter (14723): <asynchronous suspension>
E/flutter (14723): #4      Future.wait.<anonymous closure> (dart:async/future.dart)
E/flutter (14723): <asynchronous suspension>
E/flutter (14723): #5      Pay._loadConfigAssets (package:pay/src/pay.dart:45:25)
E/flutter (14723): <asynchronous suspension>
E/flutter (14723): 
`

**Comment by JlUgia** [comment]
Hi @Nisarg12, make sure to use a valid payment configuration for the button. If you are loading the configuration from a JSON file in your assets, make sure to include it in your `pubspec.yaml` (see the [example pubspec.yaml](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/pubspec.yaml#L26)), and ensure that the `provider` and `data` keys are present in your configuration (take a look at the [sample configuration files](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json))

**Comment by Nisarg12** [comment]
> Hi @Nisarg12, make sure to use a valid payment configuration for the button. If you are loading the configuration from a JSON file in your assets, make sure to include it in your `pubspec.yaml` (see the [example pubspec.yaml](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/pubspec.yaml#L26)), and ensure that the `provider` and `data` keys are present in your configuration (take a look at the [sample configuration files](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json))

Thank you @JlUgia, that was indeed the problem, the JSON file was missing both the keys. I will close this now :)

**Comment by Nisarg12** [comment]
Reopening this because when I switch to iOS from flutter inspector, the `GooglePayButton` becomes tiny, it is present in widget tree but it is once again as shown in the image above.
Android:
![image](https://user-images.githubusercontent.com/28131554/120782782-f9d88a80-c547-11eb-8852-d094167593bc.png)
iOS:
![image](https://user-images.githubusercontent.com/28131554/120782867-1379d200-c548-11eb-9b80-0384b12c7278.png)
Also, what might be causing this other blue dot at the bottom right? It doesn't appear on screens not using the plugin.

**Comment by JlUgia** [comment]
Hi @Nisarg12, this is intended. If you keep diving down the tree, you'll find that this is only the representation of an "empty" widget, `SizedBox.shrink()`, when the conditions to show the payment button are not met. This widget has no visual representation and even though it is part of the widget tree, it's not proposed for drawing, and hence does not take any unnecessary cycles from the processor.

**Comment by Nisarg12** [comment]
> Hi @Nisarg12, this is intended. If you keep diving down the tree, you'll find that this is only the representation of an "empty" widget, `SizedBox.shrink()`, when the conditions to show the payment button are not met. This widget has no visual representation and even though it is part of the widget tree, it's not proposed for drawing, and hence does not take any unnecessary cycles from the processor.

I see, what condition(s) might be unfulfilled that results it shrinking on iOS only?

**Comment by JlUgia** [comment]
The [effect is the same](https://github.com/google-pay/flutter-plugin/blob/main/pay/lib/src/widgets/pay_button.dart#L87) if the platform is set as not supported. This is currently the case for Google Pay and Apple Pay on Android and iOS respectively, although, on one hand, future providers may have support for Android and iOS, and also, if/when Web is added to the plugin, both Apple and Google Pay will have support for two platforms each:
* Apple Pay -> iOS and Web
* Google Pay -> Android and Web

Let me know if this helps.

**Comment by Nisarg12** [comment]
> The [effect is the same](https://github.com/google-pay/flutter-plugin/blob/main/pay/lib/src/widgets/pay_button.dart#L87) if the platform is set as not supported. This is currently the case for Google Pay and Apple Pay on Android and iOS respectively, although, on one hand, future providers may have support for Android and iOS, and also, if/when Web is added to the plugin, both Apple and Google Pay will have support for two platforms each:
> 
> * Apple Pay -> iOS and Web
> * Google Pay -> Android and Web
> 
> Let me know if this helps.

I am assuming this check was placed because it can be easy to forget to implement platform specific buttons causing inconsistency problems and redundant widgets. I hope to see support for both platforms sooner or later, but as of now is it better to use Platform class and conditionally place both the buttons or just have them both and one will shrink?

**Comment by JlUgia** [comment]
Your assumption is accurate. This plugin acknowledges that platform support will vary across providers, and as such, adapts to these different scenarios. Any request for additional platform support is beyond the scope of the plugin, and is preferable to do directly with each provider separately.

The plugin actually lets you choose the buttons to show in your UI, with two different integration paths:
* With the [quick integration path](https://github.com/google-pay/flutter-plugin/tree/main/pay#usage) (using the [widgets in the `pay` package](https://github.com/google-pay/flutter-plugin/tree/main/pay/lib/src/widgets)), the widgets decide whether to show based on the platform and the response from the `userCanPay` call.
* With the [custom integration path](https://github.com/google-pay/flutter-plugin/tree/main/pay#advanced-usage) (using the raw buttons on [Android](https://github.com/google-pay/flutter-plugin/tree/main/pay_android/lib/src/widgets) and [iOS](https://github.com/google-pay/flutter-plugin/tree/main/pay_ios/lib/src/widgets)), you can use the calls in the API to decide what buttons to show and when to do so.

**Comment by Nisarg12** [comment]
> Your assumption is accurate. This plugin acknowledges that platform support will vary across providers, and as such, adapts to these different scenarios. Any request for additional platform support is beyond the scope of the plugin, and is preferable to do directly with each provider separately.
> 
> The plugin actually lets you choose the buttons to show in your UI, with two different integration paths:
> 
> * With the [quick integration path](https://github.com/google-pay/flutter-plugin/tree/main/pay#usage) (using the [widgets in the `pay` package](https://github.com/google-pay/flutter-plugin/tree/main/pay/lib/src/widgets)), the widgets decide whether to show based on the platform and the response from the `userCanPay` call.
> * With the [custom integration path](https://github.com/google-pay/flutter-plugin/tree/main/pay#advanced-usage) (using the raw buttons on [Android](https://github.com/google-pay/flutter-plugin/tree/main/pay_android/lib/src/widgets) and [iOS](https://github.com/google-pay/flutter-plugin/tree/main/pay_ios/lib/src/widgets)), you can use the calls in the API to decide what buttons to show and when to do so.

Using the quick integration path, the button still occupies some considerable space estate in the UI, so I think developers would still prefer to put the manual checks for the platform the app is being run from. Anyhow, it is pretty convenient that the plugin does that on it's own nonetheless. Kuddos for that ✌🏼

**Comment by JlUgia** [comment]
Hey @Nisarg12, can you elaborate more on the space that the button occupies? When the button does not show, the resulting widget should have 0'ed dimensions and not be drawn at all. Are you experiencing something different? Can you share more details if that's the case?
Thank you!

**Comment by Nisarg12** [comment]
> Hey @Nisarg12, can you elaborate more on the space that the button occupies? When the button does not show, the resulting widget should have 0'ed dimensions and not be drawn at all. Are you experiencing something different? Can you share more details if that's the case?
> Thank you!

Yes, it most certainly does not 0 out, I am attaching the results yielded in both the cases:
1) Not shrinked:
<img width="720" alt="Screenshot_1622808438" src="https://user-images.githubusercontent.com/28131554/120802121-b12ccb80-c55f-11eb-9de9-bc487359c7ba.png">

2) Shrinked:
<img width="720" alt="Screenshot_1622810154" src="https://user-images.githubusercontent.com/28131554/120802160-bc7ff700-c55f-11eb-8a3e-d5244e993374.png">

3) Removed from the tree completely:
<img width="720" alt="Screenshot_1622808485" src="https://user-images.githubusercontent.com/28131554/120802208-ca357c80-c55f-11eb-8dc6-57fd371880c7.png">

You can take a reference of height of the Razorpay button.

**Comment by Nisarg12** [comment]
@JlUgia I just checked if it was because of me using `MainAxisAlignment.spaceEvenly` for the Column widget and turns out even though the widget is being shrunk to 0 height and width, `spaceEvenly` & `spaceAround` would still acknowledge the widget's presence and assign it some space evenly. I suggest inverting the boolean check, and render the button if the platform is same.
```dart
if (widget._isPlatformSupported) {
      return FutureBuilder<bool>(
      future: userCanPayFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          if (snapshot.data == true) {
            return Container(
              margin: widget.margin,
              width: widget.width,
              height: widget.height,
              child: widget._payButton,
            );
          } else {
            return ButtonPlaceholder(
              margin: widget.margin,
              child: widget.childOnError,
            );
          }
        }

        return ButtonPlaceholder(
          margin: widget.margin,
          child: widget.loadingIndicator,
        );
      },
    );;
}
```

**Comment by JlUgia** [comment]
Thanks for the additional detail @Nisarg12.
