### ISSUE TITLE
Execution failed for task ':pay_android:compileDebugKotlin'.

### ISSUE THREAD

**Issue by ajailee** [google-pay/flutter-plugin#53]
![Screenshot 2021-06-05 at 11 09 41 AM](https://user-images.githubusercontent.com/37687348/120881442-b422cd00-c5ee-11eb-97a7-3cbe77de7978.png)

Launching lib/main.dart on AOSP on IA Emulator in debug mode...
lib/main.dart:1
Note: /Users/ajaylee/development/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-1.1.6/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /Users/ajaylee/development/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.4/android/src/main/kotlin/io/flutter/plugins/pay_android/GooglePayHandler.kt: (172, 27): Expecting a parameter declaration
e: /Users/ajaylee/development/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.4/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (40, 28): Expecting a parameter declaration
e: /Users/ajaylee/development/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.4/android/src/main/kotlin/io/flutter/plugins/pay_android/PayMethodCallHandler.kt: (56, 52): Expecting a parameter declaration
e: /Users/ajaylee/development/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.4/android/src/main/kotlin/io/flutter/plugins/pay_android/PayPlugin.kt: (41, 79): Expecting a parameter declaration
e: /Users/ajaylee/development/flutter/.pub-cache/hosted/pub.dartlang.org/pay_android-1.0.4/android/src/main/kotlin/io/flutter/plugins/pay_android/PayPlugin.kt: (55, 67): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pay_android:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

what to do now

**Comment by JlUgia** [comment]
Hey @ajailee, the need to import the platform interface is unintended. I've created a PR to fix that and remove that need to import the `pay_platform_interface` package separately.

Take a look at https://github.com/google-pay/flutter-plugin/pull/55..
This will be part of the next minor release once merged (expected to land on Monday)

**Comment by ajailee** [comment]
@JlUgia Thanks for The information Great Work !!!

**Comment by kenaitian** [comment]
using latest everything to include Flutter 3.0 and I'm getting the following error unless pay package still depends on previous versions dependencies:

* What went wrong:
Execution failed for task ':pay_android:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
<img width="1210" alt="Screen Shot 2022-05-17 at 2 24 44 AM" src="https://user-images.githubusercontent.com/63857624/168743286-cf0efab0-e82b-4e84-b03d-dc3d88a5ae92.png">

**Comment by HaardikBhagtani** [comment]
> using latest everything to include Flutter 3.0 and I'm getting the following error unless pay package still depends on early dependencies:
> 
> * What went wrong:
>   Execution failed for task ':pay_android:compileDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > Compilation error. See log for more details
> 
> <img alt="Screen Shot 2022-05-17 at 2 24 44 AM" width="1210" src="https://user-images.githubusercontent.com/63857624/168743286-cf0efab0-e82b-4e84-b03d-dc3d88a5ae92.png">

same I am also having this problem @JlUgia
