### ISSUE TITLE
Not Working on IOS 

### ISSUE THREAD

**Issue by enviro-apps** [google-pay/flutter-plugin#56]
Hello I get the following error when trying to open Apple Pay

Unhandled Exception: PlatformException(paymentError, Failed to present payment controller, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      PayMethodChannel.showPaymentSelector (package:pay_platform_interface/pay_channel.dart:64:27)
<asynchronous suspension>
#3      _PurchaseScreenState.payment (package:lalamu/pages/purchase/view/purchase_screen.dart:42:33)
<asynchronous suspension>

**Comment by JlUgia** [comment]
Hi @enviro-apps, do double check that your Apple Pay config is accurate. See this related [StackOverflow post](https://stackoverflow.com/questions/42305132/unable-to-present-apple-pay-authorization-controller) for `PKPaymentAuthorizationController`'s `present method.

If you continue to see issues, feel free to share your configuration in this thread (make sure to remove any secret values first.

**Comment by enviro-apps** [comment]
Thank you, I will have a look. There might be a high possibility that my config is wrong however in the simulator everything is working fine

**Comment by tudor07** [comment]
I have the same issue, @JlUgia can you reopen this ticket?

**Comment by enviro-apps** [comment]
@tudor07 I solved it by agreeing to some terms on the Apple Developer site

**Comment by tudor07** [comment]
For future people that may run into this:
My issue was that I had invalid config in `merchantCapabilities` in `default_payment_profile_apple_pay.json` file.
