### ISSUE TITLE
Needs to handle the state changes

### ISSUE THREAD

**Issue by mytales** [google-pay/flutter-plugin#58]
Need to handle the state changes like new subscriptions, renewals, Expirations, and Cancellations to ensure that the state is kept in-sync. Is there documentation explaining how we can achieve that using the "pay" package?

**Comment by JlUgia** [comment]
Hello @mytales. The payment technologies in the `pay` plugin, facilitate using card details saved under your customers' accounts with your payment processor of choice (eg.: Use your user A's Visa card to create an order with your payment processor). These technologies do not take care of the processing itself, and hence, recurring billing schemes are managed as usual: typically through your PSP, or yourself it your business processes payments directly.

What payment processor or gateway are you using to process payments?

**Comment by mytales** [comment]
I am planning to use IAP (G Pay for android and Apple Pay for iOS). So I want to validate the user's subsciption and keep my application in-sync with the state. So is there any feature provided from this package so that I can subscribe to the stream and update stream accordingly? Or we have to use other library if we want to handle this in the application?

**Comment by JlUgia** [comment]
The `pay` plugin facilitates payments outside of the scope of the application stores. For IAP, take a look at the [in_app_purchase](https://pub.dev/packages/in_app_purchase) package. Hope it helps.
