### ISSUE TITLE
calling userCanPay (as well as other client methods) leads to PlatformException

### ISSUE THREAD

**Issue by vanomak** [google-pay/flutter-plugin#60]
version 1.0.5

E/flutter (26185): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(10, 10: , null, null)
E/flutter (26185): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (26185): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (26185): <asynchronous suspension>
E/flutter (26185): #2      PayMethodChannel.userCanPay (package:pay_platform_interface/pay_channel.dart:48:12)
E/flutter (26185): <asynchronous suspension>

**Comment by JlUgia** [comment]
This looks like an error on your configuration for Android. Take a look at the logs on Android for more details on the error:
[`adb -d logcat -s WalletMerchantError`](https://developers.google.com/pay/api/android/support/troubleshooting#request-failed).

**Comment by vanomak** [comment]
> This looks like an error on your configuration for Android. Take a look at the logs on Android for more details on the error:
> [`adb -d logcat -s WalletMerchantError`](https://developers.google.com/pay/api/android/support/troubleshooting#request-failed).

Thank you Jose!
