### ISSUE TITLE
Facing 'Unexpected Developer Error' issue

### ISSUE THREAD

**Issue by Ishwar398** [google-pay/flutter-plugin#62]
I've just started using the Pay package for my Flutter application. And am facing this issue.
![image](https://user-images.githubusercontent.com/13011254/122801486-cc2e6800-d2e1-11eb-86bc-e4b14dc32273.png)

Please help me resolve the issue.

**Comment by JlUgia** [comment]
(Duplicate of #48)
Hi @Ishwar398 , it seems that there is an error in your configuration. Take a look at the logs, filtering for `WalletMerchantError` to learn about the concrete cause. You can check them on Android Studio (or other IDE), or directly using the terminal: `adb -d logcat -s WalletMerchantError`.

**Comment by deucks** [comment]
I had a similar issue, had a problem with paymentItems. Where the PaymentItem list I created for iOS worked, but Android threw an error.
