### ISSUE TITLE
Can't obtain a Stripe token with Apple Pay

### ISSUE THREAD

**Issue by Alessandro-v** [google-pay/flutter-plugin#65]
I'm using Apple/Google Pay to generate a Stripe's charge, then I'm passing the token to our backend that takes care of the payment process. 

Here's the GPay flow:

Inside the `google_pay_config.json` we've all infos about Stripe:

```
"allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
               "gateway": "stripe",
	       "stripe:version": "2018-11-08",
	       "stripe:publishableKey": "stripe_key"
      }
   }
]
```

Then I'm creating all the `PaymentItems`, getting a `PaymentResult` and finally from `PaymentResult` I can get a token to pass to the backend to complete the payment.

```
final token = paymentResult['paymentMethodData']['tokenizationData']['token'];
final tokenJson = Map.castFrom(json.decode(token));
String tokenId = tokenJson['id'];
```

How can I obtain that token using Apple Pay since I couldn't find any way to specify the Stripe data inside `apple_pay_config.json`?

**Comment by JlUgia** [comment]
Hello @Alessandro-v, using the payment result to create orders is a process that varies by PSP.

### Using client libraries
Some of them, like Stripe, offer SDKs and client libraries that simplify that step. In fact, Stripe recently released a [plugin for Flutter](https://github.com/flutter-stripe/flutter_stripe#pay-plugin-support) too (see the comment below). The plugin from Stripe integrates seamlessly with the `pay` plugin, by offering convenience methods to complete the payment operation with the payment result returned by the `showPaymentSeletor` method. Take a look at the [`pay` section in the README](https://github.com/flutter-stripe/flutter_stripe#pay-plugin-support) to see a practical example. For Apple Pay, the token can be found under `paymentResult.token.paymentData`.

### Using backend APIs
Alternatively, you can perform the same operation calling the APIs directly from your backend (which is a common path supported by most PSPs). For Stripe, that means creating a payment method from a token, and using it to confirm the payment or create a payment intent:
1. Create a [token resource](https://stripe.com/docs/api/tokens/object), passing the result received with the `pk_token` param. Take a look at how [this is done in the Stripe SDK for iOS](https://github.com/stripe/stripe-ios/blob/8ca9931984949fbce44c342d5cecdada03cda18f/Stripe/STPAPIClient.swift#L138) and the [parameters](https://github.com/stripe/stripe-ios/blob/591f54d11f6f60be609e294f7dd7570c0ad32b49/Stripe/STPAPIClient%2BApplePay.swift#L160) used.
2. Create a [payment method](https://stripe.com/docs/api/payment_methods) with the token created previously. See an [example of that same request in the Stripe SDK for iOS](https://github.com/stripe/stripe-ios/blob/591f54d11f6f60be609e294f7dd7570c0ad32b49/Stripe/STPAPIClient%2BApplePay.swift#L60) for reference.
3. Confirm the payment or create a [payment intent] with the new payment method. Take a look at the [API docs for creating a new intent with a payment method](https://stripe.com/docs/api/payment_intents/create).

//cc'ing @jamesblasco @thorsten-stripe for visibility and additional context.

**Comment by Alessandro-v** [comment]
Thank you!! We're still waiting for an [answer](https://github.com/flutter-stripe/flutter_stripe/issues/164) on the Stripe repo to manage the Apple Pay flow.

**Comment by JlUgia** [comment]
Hi @Alessandro-v, the Stripe library for Flutter has added [specific means to create a payment method directly from the Apple Pay token](https://github.com/flutter-stripe/flutter_stripe/blob/2ae832a6b25b331616f6344efbe19d5c982cd89e/example/lib/screens/wallets/apple_pay_screen_plugin.dart#L74). See #85 for more info.

**Comment by Alessandro-v** [comment]
Thanks!!!!

**Comment by JlUgia** [comment]
Closing this issue.
Feel free to re-open if the issue stands.
