### ISSUE TITLE
Google pay support for iOS

### ISSUE THREAD

**Issue by Frostedfox** [google-pay/flutter-plugin#66]
We need support for Google pay in Apple devices.
There are countries where Apple pay isn't supported and people use Google pay instead extensively
Especially in countries like India where Google pay is goto payment interface in both android and Apple users than the app provided by the Indian government for UPI transactions

And Google pay is the leading UPI provider in India contributing for more than 50% of the transactions in the country

**Comment by neiljaywarner** [comment]
@RedBrogdon  this is pretty confusing since Google Pay flutter app is on the rise so much and diversifying; is this on the roadmap for this year?

**Comment by neiljaywarner** [comment]
in addition, the announcement specifically mentions ios and android and does not mention apple pay which meakes it more confusing https://developers.googleblog.com/2021/05/google-pay-introduces-flutter-plugin-for-payments.html

"Our open source Flutter plugin simplifies the addition of payments to Flutter apps on iOS and Android.

The plugin gives you the ability to add functionality to your apps across platforms ...easily reap the benefits of Google Pay"

**Comment by JlUgia** [comment]
This plugin facilitates the integration of [Google Pay](g.co/pay/api) and [Apple Pay](https://developer.apple.com/documentation/passkit/apple_pay/offering_apple_pay_in_your_app) to third party applications selling physical goods, operating outside of the UPI scheme.
The plugin is separate and unrelated to the [Google Pay application itself](https://pay.google.com/about/).

Could you clarify your ask? Is it related to the Google Pay app, the UPI or the third-party API integration?

**Comment by Frostedfox** [comment]
just need google pay for ios devices along with apple pay

**Comment by Frostedfox** [comment]
apple users in India can't use apple pay. That's why need an alternative payment option like google pay

**Comment by jakub-cosmose** [comment]
Is there any update on this? There's some documentation about Google Pay on iOS (https://developers.google.com/pay/india/api/ios/in-app-payments), but I don't see any way to implement it using this plugin in the current version.

**Comment by bhushan-qw** [comment]
we can integrate the google pay in IOS device through stripe in flutter?? , I am able to make processing in android thorugh google pay but when try in IOS device the google pay get error 
  Google Pay Error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: You must provide the `applePay` parameter., message: You must provide the `applePay` parameter., stripeErrorCode: null, declineCode: null, type: null))

there is a way to integrate google pay in IOS device through Stripe Gateway
