### ISSUE TITLE
[ApplePay] Provide transactionIdentifier in paymentResult

### ISSUE THREAD

**Issue by hkhars** [google-pay/flutter-plugin#68]
I am trying to integrate with a payment gateway that requires **transactionIdentifier** along with **paymentData** & **paymentMethod**

Request your support to add it to the  Payment Result.

Please find reference below:
https://developer.apple.com/documentation/passkit/pkpaymenttoken/1617003-transactionidentifier

**Comment by JlUgia** [comment]
Hi @hkhars, thank you for filing the issue. I've added it to the pipeline.
What's the payment gateway you are working with? Can you share a link to their docs including the `transactionIdentifier`?

**Comment by victorinyushin** [comment]
Hi @JlUgia 
For example cloudpayments uses this in his cdk to generate a cryptogram for payment through their service
[sdk git](https://github.com/cloudpayments/SDK-iOS/blob/master/sdk/sdk/Utils/PKPaymentConverter.m) line 36

**Comment by JlUgia** [comment]
Thank you @victorinyushin, [v1.0.10](https://pub.dev/packages/pay/changelog), adds the `transactionIdentifier` to the Apple Pay result.
