### ISSUE TITLE
How to change the currency used for payment

### ISSUE THREAD

**Issue by mzj-xk** [google-pay/flutter-plugin#69]

**Comment by JlUgia** [comment]
Hi @mzj-xk, the currency is part of your configuration. Take a look at the configurations for [Apple Pay](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json#L9) and [Google Pay](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_google_pay.json#L34) in the example included in the repo.

**Comment by mzj-xk** [comment]
> Hi @mzj-xk, the currency is part of your configuration. Take a look at the configurations for [Apple Pay](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_apple_pay.json#L9) and [Google Pay](https://github.com/google-pay/flutter-plugin/blob/main/pay/example/assets/default_payment_profile_google_pay.json#L34) in the example included in the repo.

thank you
