### ISSUE TITLE
WalletMerchantError when trying to make a payment

### ISSUE THREAD

**Issue by wa11breaker** [google-pay/flutter-plugin#70]
I am getting a WalletMerchantError when making a payment, it's working fine when the environment is set to   ##TEST.

`WalletMerchantError: Error in loadPaymentData: PaymentDataRequest.allowedPaymentMethods[0].parameters.allowedAuthMethods[0] = MASTERCARD is not a valid enum value for this field.`

json
```
{
    "provider": "google_pay",
    "data": {
        "environment": "PRODUCTION",
        "apiVersion": 2,
        "apiVersionMinor": 0,
        "allowedPaymentMethods": [
            {
                "type": "CARD",
                "tokenizationSpecification": {
                    "type": "PAYMENT_GATEWAY",
                    "parameters": {
                        "gateway": "example",
                        "gatewayMerchantId": "Merchant id form dashboard"
                    }
                },
                "parameters": {
                    "allowedCardNetworks": [
                        "VISA",
                        "MASTERCARD"
                    ],
                    "allowedAuthMethods": [
                        "MASTERCARD",
                        "VISA"
                    ],
                    "billingAddressRequired": false,
                    "billingAddressParameters": {
                        "format": "FULL",
                        "phoneNumberRequired": true
                    }
                }
            }
        ],
        "merchantInfo": {
            "merchantId": "Merchant id form dashboard",
            "merchantName": "Merchant Name"
        },
        "transactionInfo": {
            "countryCode": "US",
            "currencyCode": "USD"
        }
    }
}
```
code 
```
 void makePayment() async {
    Pay _payClient = Pay.withAssets([
      'default_payment_profile_google_pay.json',
    ]);

    final _paymentItems = [
      PaymentItem(
        label: 'Total',
        amount: '100',
        status: PaymentItemStatus.final_price,
      )
    ];

    try {
      final result = await _payClient.showPaymentSelector(
        provider: PayProvider.google_pay,
        paymentItems: _paymentItems,
      );
      print(result.toString());
    } catch (e) {
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('An error occourred')));
    }
  }
```
EDIT:
Tried removing master cart from the json array and reinstalled the app but now it show 
`c07-16 18:20:14.125 22243 22243 W WalletMerchantError: Error in loadPaymentData: PaymentDataRequest.allowedPaymentMethods[0].parameters.allowedAuthMethods[0] = VISA is not a valid enum value for this field.`

**Comment by socsieng** [comment]
`allowedAuthMethods` must be one of the following:

- `PAN_ONLY`: This authentication method is associated with payment cards stored on file with the user's Google Account. Returned payment data includes personal account number (PAN) with the expiration month and the expiration year.
- `CRYPTOGRAM_3DS`: This authentication method is associated with cards stored as Android device tokens. Returned payment data includes a 3-D Secure (3DS) cryptogram generated on the device.

See: https://developers.google.com/pay/api/android/reference/request-objects#CardParameters
