### ISSUE TITLE
Unable to get postalAddress from Apple Pay

### ISSUE THREAD

**Issue by hyphense** [google-pay/flutter-plugin#72]
When i add postalAddress to my payment profile like this:

```
{
  "provider": "apple_pay",
  "data": {
    "merchantIdentifier": "merchant.mxxxxx",
    "displayName": "xxxxx",
    "merchantCapabilities": ["3DS", "debit", "credit"],
    "supportedNetworks": ["amex", "visa", "discover", "masterCard"],
    "countryCode": "DE",
    "currencyCode": "EUR",
    "requiredBillingContactFields": ["postalAddress"],
    "requiredShippingContactFields": ["emailAddress", "name", "postalAddress"],
  }
}
```

the Apple Pay sheet shows and lets me select a shipping address and a payment address.

I use this ApplePayButton:

```
pay.ApplePayButton(
          height: 50,
            paymentConfigurationAsset: 'apple_pay_payment_profile.json',
            paymentItems: _paymentItems,
            style: pay.ApplePayButtonStyle.black,
            type: pay.ApplePayButtonType.buy,
            margin: const EdgeInsets.only(top: 15.0),
            onPaymentResult: onApplePayResult,
            loadingIndicator: const Center(
              child: CircularProgressIndicator(),
            ),
```

The paymentResult in onApplePayResult contains the name, email and other data but no address.
How can i obtain it?

**Comment by mklepaczko** [comment]
I also would like to be able to get these info.

**Comment by ncuillery** [comment]
Found it!

"postalAddress" is missing in this serialization method.

**Comment by JlUgia** [comment]
Can you elaborate @ncuillery?

**Comment by ncuillery** [comment]
Sorry, the link didn't work for some reasons.

I placed a breakpoint at this line:
https://github.com/google-pay/flutter-plugin/blob/2a8f056c15b29e512d6f2577d9ead21e41235561/pay_ios/ios/Classes/PaymentHandler.swift#L189

The `payment` variable does contain the `postalAddress` of the `billingContact` as expected, but then the `toDictionnary()` method ignores this data:
https://github.com/google-pay/flutter-plugin/blob/2a8f056c15b29e512d6f2577d9ead21e41235561/pay_ios/ios/Classes/PaymentHandler.swift#L245-L256

So the data sent back to Flutter doesn't contain the address.

PR is on its way.

**Comment by JlUgia** [comment]
See [`pay` v1.0.8](https://pub.dev/packages/pay/changelog) and [`pay_ios` v1.0.6](https://pub.dev/packages/pay_ios/changelog).
