### ISSUE TITLE
Direct Integration

### ISSUE THREAD

**Issue by enviro-apps** [google-pay/flutter-plugin#75]
Hello, I have a general question. While creating a release version of my app, I saw that in the google business console it was saying did you used a payment provider or a direct integration. So what I want to ask is, is there a way to directly integrate without having to call a stripe backend etc.

**Comment by JlUgia** [comment]
Hello @enviro-apps, Stripe is not the only supported processor. You can integrate with a number of payment gateways both on [Google Pay](g.co/pay/processors) and [Apple Pay](https://developer.apple.com/apple-pay/payment-platforms/).

On integrating without a 3rd party payment gateway, take a look at the related docs from [Google Pay](https://developers.google.com/pay/api/android/guides/resources/payment-data-cryptography) and [Apple Pay](https://developer.apple.com/library/archive/ApplePay_Guide/ProcessPayment.html).
