### ISSUE TITLE
How to get the Stripe token id?

### ISSUE THREAD

**Issue by michealchow2324** [google-pay/flutter-plugin#85]
Im trying to use google pay to create payments in Stripe.
i got the error like this 

> Error: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Invalid token id: tok_1JTltJEmr43pL7PJoO3LqsjE, message: Invalid token id: tok_1JTltJEmr43pL7PJoO3LqsjE, stripeErrorCode: null, declineCode: null, type: invalid_request_error)

when the app ran the below codes:

> // 3. Confirm Google pay payment method
        await Stripe.instance.confirmPayment(
          clientSecret,
          params,
        );

Does anyone knows what seems to be the problem?
This is my google_pay_payment_profile.json
> {
  "provider": "google_pay",
  "data": {
    "environment": "TEST",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2020-08-27",
            "stripe:publishableKey": {my publishable key}
          }
        },
        "parameters": {
          "allowedCardNetworks": ["VISA", "MASTERCARD"],
          "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
          "billingAddressRequired": false,
          "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": true
          }
        }
      }
    ],
    "merchantInfo": {
      "merchantId": {my merchant id},
      "merchantName": {my merchant name}
    },
    "transactionInfo": {
      "countryCode": "US",
      "currencyCode": "USD"
    }
  }
}

**Comment by JlUgia** [comment]
Hi @michealchow2324, are you creating a `PaymentMethodParams` object to pass it to `confirmPayment` as mentioned in the [Stripe plugin](https://github.com/flutter-stripe/flutter_stripe#pay-plugin-support)?

/cc @jonasbark @jamesblasco to share additional insights.

**Comment by jamesblasco** [comment]
Hello all! The payment result does not contain a Stripe token id, only the Apple tokenized card data. 
To retrieve the tokenized stripe id we have added a new method in the latest release `createApplePayToken`.

Feel free to check the example from the repo:

https://github.com/flutter-stripe/flutter_stripe/blob/2ae832a6b25b331616f6344efbe19d5c982cd89e/example/lib/screens/wallets/apple_pay_screen_plugin.dart#L74

**Comment by JlUgia** [comment]
The problem seems to be happening on Google Pay @jamesblasco.
Is there an analogous method for the Google Pay token too?
If so, it'd be worthwhile updating the example in the readme too.

**Comment by JlUgia** [comment]
@michealchow2324, take a look at the example on the Stripe plugin library, on [how to use the payload received from Google Pay to create a payment](https://github.com/flutter-stripe/flutter_stripe/blob/2ae832a6b25b331616f6344efbe19d5c982cd89e/example/lib/screens/wallets/google_pay_screen.dart).

**Comment by JlUgia** [comment]
Hi @michealchow2324, did that help solve the issue?
Closing this issue. Feel free to reopen if needed.
