### ISSUE TITLE
Get a lot of errors in pay_ios-1.0.4

### ISSUE THREAD

**Issue by sgs2007** [google-pay/flutter-plugin#88]
I get many errors when start debugging app:
Xcode's output:
↳
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:121:15: error: 'donate' is only available in iOS 10.2 or newer
          return .donate
                  ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:121:15: note: add 'if #available' version check
          return .donate
                  ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:112:22: note: add @available attribute to enclosing static method
      public static func fromString(_ buttonType: String) -> PKPaymentButtonType? {
                         ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:111:1: note: add @available attribute to enclosing extension
    extension PKPaymentButtonType {
    ^

**Comment by sgs2007** [comment]
also:
          return .book
                  ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:125:15: note: add 'if #available' version check
          return .book
                  ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:112:22: note: add @available attribute to enclosing static method
      public static func fromString(_ buttonType: String) -> PKPaymentButtonType? {
                         ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:111:1: note: add @available attribute to enclosing extension
    extension PKPaymentButtonType {
    ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:127:15: error: 'subscribe' is only available in iOS 12.0 or newer
          return .subscribe
                  ^
    /Users/sgs20071/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.4/ios/Classes/ApplePayButtonView.swift:127:15: note: add 'if #available' version check
          return .subscribe

**Comment by sgs2007** [comment]
Also i tried run project via xcode and get two error:
1) Header 'pay_ios-Swift.h' not found and 2)could not build module 'pay ios',

**Comment by JlUgia** [comment]
Hi @sgs2007, how are you using the project? Note that the `pay_ios` package does not have an example application that can be opened or executed by itself independently from Xcode. If you are trying to open and run code from the library, make sure to run the [preliminary steps](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm) first.

On the version mismatch issues, we're taking a look, what target version are you using?

**Comment by JlUgia** [comment]
The minimum version of iOS in the package is 12.0, so if setup correctly, those errors needn't show up.
Do you have a lower version configured elsewhere?

**Comment by sgs2007** [comment]
Hello,
I just want use apple pay button from package for my applicanition. I made all actions which was described in step 1 ( Take a look at the integration requirements.
Create a merchant identifier for your business.
Create a payment processing certificate to encrypt payment information.) but when i run debuggin project I get stack of errors which I discribed in my first comment.

**Comment by sgs2007** [comment]
If the problem is in the IOS version. Could you tell me how to change it? In my simulator IPhone 12 pro max current version of IOS is 14.7

**Comment by JacksonHiew** [comment]
@sgs2007 I am also encountring this issue and I found out that my the target version that I put in Podfile is lower than 12. Changing it to 12 should work.

Eg:
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'

&

platform :ios, '12.1'

**Comment by tudor07** [comment]
@JacksonHiew does it work if you change deployment target to 12.1?

**Comment by sgs2007** [comment]
If I understood everything correctly

> @sgs2007 I am also encountring this issue and I found out that my the target version that I put in Podfile is lower than 12. Changing it to 12 should work.
> 
> Eg:
> config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
> 
> &
> 
> platform :ios, '12.1'

If I understood everything correctly. I open Pods via Xcode go to Build settings then go to Levels and change  IOS Deployment Target on 14.4, Is it correct?

**Comment by tudor07** [comment]
I created this PR to fix this issue: https://github.com/google-pay/flutter-plugin/pull/91

**Comment by JlUgia** [comment]
Hi everyone, and thank you for the contributions @tudor07.
To set the context appropriately, the decision to go with a minimum iOS version of 12 is founded on avoiding adding unjustified complexity. Note that as of June, 3rd this year, devices using iOS13 is above 98%, with 12 being presumably beyond 99%.
Said that, I think it's reasonable to support an earlier version as long as there's a solid rationale behind. @tudor07, @sgs2007, @JacksonHiew do you have specific requirements that prevent you from using more recent versions of iOS?

**Comment by tudor07** [comment]
@JlUgia 
I understand your point and I agree with you. Usually it's a good idea to drop support for these lower version especially when supporting them requires a significant amount of overhead or increases the code complexity. In this specific scenario though the changes are trivial. There are some values in some enums (some of them mostly unused). I don't really see a compelling reason not to include these changes. It does not increase code complexity and it does not make code harder to maintain (there already are some `#if available` check for iOS 14, adding a few more for iOS 12 does not impact the code in a negative way). Let me know what do you think.

**Comment by JacksonHiew** [comment]
> If I understood everything correctly
> 
> > @sgs2007 I am also encountring this issue and I found out that my the target version that I put in Podfile is lower than 12. Changing it to 12 should work.
> > Eg:
> > config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
> > &
> > platform :ios, '12.1'
> 
> If I understood everything correctly. I open Pods via Xcode go to Build settings then go to Levels and change IOS Deployment Target on 14.4, Is it correct?

Not just that, if you have specify any "version related thing" (Eg: in Podfile), you need to set it at least from 12.0

**Comment by JacksonHiew** [comment]
> If I understood everything correctly
> 
> > @sgs2007 I am also encountring this issue and I found out that my the target version that I put in Podfile is lower than 12. Changing it to 12 should work.
> > Eg:
> > config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
> > &
> > platform :ios, '12.1'
> 
> If I understood everything correctly. I open Pods via Xcode go to Build settings then go to Levels and change IOS Deployment Target on 14.4, Is it correct?

Sorry, not sure about that since I usually edit that file directly over Visual Studio Code.

**Comment by sgs2007** [comment]
> > If I understood everything correctly
> > > @sgs2007 I am also encountring this issue and I found out that my the target version that I put in Podfile is lower than 12. Changing it to 12 should work.
> > > Eg:
> > > config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
> > > &
> > > platform :ios, '12.1'
> > 
> > 
> > If I understood everything correctly. I open Pods via Xcode go to Build settings then go to Levels and change IOS Deployment Target on 14.4, Is it correct?
> 
> Sorry, not sure about that since I usually edit that file directly over Visual Studio Code.
Could you tell me how can I find needed row for editing via VS Code.

**Comment by JlUgia** [comment]
I think that's reasonable @tudor07.
Reviewing and merging #91
