### ISSUE TITLE
Unrecognized app. Please make sure you trust this app before proceeding #455

### ISSUE THREAD

**Issue by vaibhavmali123** [google-pay/flutter-plugin#93]
Log {"signature":"MEQCICzhmoYWxb4vG9IHzEEilfkKGSNCD78ZvglqnohA2rq5AiAow/fRv340jiXNl1tpJryIAT4/S7QNikKB8PNdVsSZPg\u003d\u003d","protocolVersion":"ECv1","signedMessage":"{\"encryptedMessage\":\"iv4J1uBmZGsNO4UJw4JYRmwJyf2TTf1KWO1KWTUm/k+0h4GXIU3a3mtoSYOv8vsT81bdRJGmUdPw4m3RFMzp7aQcSaT0nYImgHKcd4ikmOOPI3xMoxg8akhFR4tVjdUB4+D1E03J8QwUKn69DLKKiB+2vCztVXuM1XaEEdWYt6vy0d2u9rMgEf+CvuwJu9eDNsidaHGp95BzfNn0O7yVehKrSnW2G2AbaMjylKWbZ+EsGqulpx+lqrs5//TnNt/nWb6G6/WsYCcDXpkpDPu/ipavvEjVThqmQObJPdJxIPYR9FjCjyJvkffctZshJdUYHSu5ZR1qTJW7USB35EmkFb40Uam8Jg5PvbqxxsioQ8jeQkKQdZsUu6MBk8byHEoAjAvv/rVZ4yE0fJeNw3y5Hn3RIY3VtJx1prm740av614eJfLCl7apy01et57TKDzD5AZuHTIx1gLADlU\\u003d\",\"ephemeralPublicKey\":\"BHV/YrV7zcP31132pWiri3hw4k9Z48v4s4KV4w5m3XBGEa27rCcH3v6Sfqxn2J4bSTHDp3i54A3d9KAlVwNIkcc\\u003d\",\"tag\":\"hIaXJ1/0xwN2YXYF84twoQm5OZWSt6KA55Ttn12b8g4\\u003d\"}"}}, type: CARD, info: {
I/flutter (23619): VISA, cardDetails: 5111, billingAddress: {phoneNumber: +91 93255 09271, address3: , sortingCode: , address2: 5, countryCode: IN, address1: Na, postalCode: 413504, name: vaibhav mali, locality: Pune, administrativeArea: Maharashtra}}}}

**Comment by JlUgia** [comment]
Hello @vaibhavmali123, I'd recommend to avoid including full production responses publicly.

The message you are referring to appears when you operate in `TEST` mode (take a look at the [troubleshooting guide](https://developers.google.com/pay/api/android/support/troubleshooting)). You can get your application approved for production through [Google Pay's Business Console](https://pay.google.com/business/console).
