### ISSUE TITLE
Google pay IOS widget for instant payments

### ISSUE THREAD

**Issue by alpha2320** [google-pay/flutter-plugin#94]
Hey, I am a developer as well as a GPay user I really feel the need if there could be an ios widget for an instant payment where the user taps on it and automatically opens the scan QR code feature.

somewhat similar to Paytm 😄 

![IMG_D43924B263E0-1](https://user-images.githubusercontent.com/58825698/135080353-f89cc7b6-8659-4ab9-856d-d65a0a38b71c.jpeg)

let me know If I could help with this 😄

**Comment by JlUgia** [comment]
Hello @alpha2320, thank you for the suggestion.
This feature would need to be added to Google Pay as a product, and as such it's out of scope for this plugin. 
Here are [some resources](https://support.google.com/pay/answer/7644089) to submit feedback about the product.

**Comment by alpha2320** [comment]
@JlUgia wanted this feature badly learnt flutter and swift now I would be looking forward to on working on this issue 🥂
